### ISSUE TITLE
Tasks app should follow the same theme as owncloud

### ISSUE THREAD

**Issue by seal20** [owncloud/tasks#102]
Even if I like the fonts and general style of the task apps. I think it will be better if it follows the same general style that owncloud, especially the fonts. Now the tasks feels very polished but a little different from the rest.

Thanks for the nice app.

**Comment by nodiscc** [comment]
@seal20 @raimund-schluessler just a reminder that this was required by @jancborchardt in https://github.com/owncloud/core/issues/9827#issuecomment-49979159, to allow this app to become the official owncloud tasks app.

**Comment by jancborchardt** [comment]
@raimund-schluessler any plans for this? Would be cool to get the tasks app rolling again and make it look fitting with ownCloud. :)

**Comment by raimund-schluessler** [comment]
I am still not sure what you really mean with this. Are there any guide lines which I should follow (like colors or margins or anything)?

I must admit that I like the app just as it looks now (otherwise I would have changed it ;) but feel free to make concise suggestions for improvements.

**Comment by onny** [comment]
The task app has at least a different style than, for example, the news app. And I also prefere a common theme for all owncloud apps, even though the owncloud default theme might be not yet the best one.
![tasks_content](https://cloud.githubusercontent.com/assets/757752/6275298/daf09a4e-b875-11e4-932f-1941f0df8684.png)
![tasks_menu](https://cloud.githubusercontent.com/assets/757752/6275299/db0e5a70-b875-11e4-80dd-0525a465de21.png)

**Comment by jancborchardt** [comment]
@onny thank you for posting the comparison screenshots. That’s exactly what I mean.

@raimund-schluessler if you use the standard HTML, the proper style will be used automatically. Check the [HTML & CSS guidelines](https://doc.owncloud.org/server/8.0/developer_manual/app/css.html#standard-layout).

**Comment by stefan-niedermann** [comment]
any progress on this issue? I'd like to use the app, but i hate that it feels like a foreign body in oc...

**Comment by jancborchardt** [comment]
@raimund-schluessler I’d be happy to do some hacking with you on this. I guess you’re in Germany so we could even meet? Either at the [ownCloud conf](https://owncloud.org/conf/), or when you’re in Munich (am in northern Germany soon as well), or I could visit you. :)

**Comment by raimund-schluessler** [comment]
Sorry guys, I don't have much time at the moment to work on the app. And when I work on the app it will be for adapting it to oC 8.1, as this is far more important than the style imho, see https://github.com/owncloud/tasks/pull/159.

@jancborchardt I live in Germany, to be more exact in Dresden ;) I thought about visiting ownCloud conf, but I cannot promise anything at the moment.

**Comment by jancborchardt** [comment]
@raimund-schluessler well with living so close you better come! :) Last year we offered 80% travel funding for contributors and we’ll hopefully do that again.

**Comment by enoch85** [comment]
@jancborchardt 

> Last year we offered 80% travel funding 

Really? Does that include me? :angel:

**Comment by jancborchardt** [comment]
@enoch85 as it seems like you contribute a ton to ownCloud, yes. :) We are in the planning phase so we need to make sure we can actually handle that – but for everyone who requires travel funding we try to support them. Ideal would be if you then register for the conf at https://owncloud.org/conf/ and submit a talk (on whatever you would like to present). :)

**Comment by enoch85** [comment]
@jancborchardt Nice! We'll talk more about this in chat tonitght. :)

**Comment by jancborchardt** [comment]
@Henni are you interested in looking into this maybe?

**Comment by Henni** [comment]
I'm already working on this :)

**Comment by jancborchardt** [comment]
Aaah great! If you’re at the meetup on wednesday I can also help you, if you need. :)

**Comment by onny** [comment]
![owncloud-tasks-owncloud-theme](https://cloud.githubusercontent.com/assets/757752/7789445/44d8e884-0250-11e5-8fe2-fdb1500a2798.png)
Here's a screenshot of Hennis pull request. Thank you Henni, I'll have a closer look into your really nice work soon!

**Comment by raimund-schluessler** [comment]
I commented on the changes on #171

**Comment by jancborchardt** [comment]
Great stuff on merging the sidebar changes already! :) Looking forward to have the main view and the rest also look more like ownCloud. Great work @henni @raimund-schluessler! :)

**Comment by Henni** [comment]
We started fixing this with the navigation bar in version 0.7 and I'm looking forward to completing this in v0.8!

**Comment by jancborchardt** [comment]
:rocket:

**Comment by raimund-schluessler** [comment]
I think the app pretty much looks like owncloud now. Please state what you think should be improved in a new issue.
