### ISSUE TITLE
Use X- Prefix for non-standard parameters in comments

### ISSUE THREAD

**Issue by David-Development** [owncloud/tasks#105]
I'm the developer of the TaskSync Android App and there are some issues when I'm using your comment functionality in ownCloud. The iCal4j Library is unable to parse those entrys because you haven't specified the X- Prefix for custom attributes.

Below is an example of a valid comment:
COMMENT;X-ID=1;X-USERID=admin;X-DATE-TIME=20141123T110631Z:Kommentaaar!
and this is what you app generates:
COMMENT;ID=1;USERID=admin;DATE-TIME=20141123T110631Z:Kommentaaar!

After this small change the tasks can be synced. Is it possible to use this format in your web-app as well? Otherwise my users won't be able to sync todo's with comments properly.

**Comment by raimund-schluessler** [comment]
@David-Development Could you please test #121 if it fixes the issue. Please escpecially test the update script if it updates old comments properly and does not break anything. Would be also good to test it for multiple users and maybe shared calendars too (And don't use it on your production environment yet). Thanks.

**Comment by raimund-schluessler** [comment]
@David-Development ping :)

**Comment by David-Development** [comment]
@raimund-schluessler  Ah damn sorry for the delay! Thanks for fixing this issue. I'm going to test it within the next two days (sorry I'm currently really busy).

**Comment by raimund-schluessler** [comment]
No problem, take your time. It will take some time until the next release.

**Comment by David-Development** [comment]
@raimund-schluessler I tested the update script with a few todo's and it's working fine. Nice work! Tested also with two users and a shared calendar (Both users created comments in the shared cal/todo).
Everything is working, awesome!

**Comment by raimund-schluessler** [comment]
Thanks for testing. I will merge it this evening into master and stable7.
