### ISSUE TITLE
Shared tasks lists doesnt follow permission restrictions

### ISSUE THREAD

**Issue by ouinouin** [owncloud/tasks#108]
Hi,
While sharing a calendar to another owncloud user and restricting it to read only for the user, the calendar cant be edited by the other user, thats fine.

Now while you are going on the tasks shared with the same calendar, the tasks cannot be removed (read only), but they ca still be ticked as "done" by the other user. I dont expect this behavior since the other user shouldnt be able to alter anything on the task list.

This behavior stops me to show my task list to some "guest" users on my owncloud server since they can alter the status of my tasks.

**Comment by chaosjug** [comment]
There are two other issues with regard to permissions:
* I can edit the text from tasks from read-only calendars. The change stays there until I switch to another app.
* The calendar app respects privacy settings in events. So a event in a shared calendar that is set to private is not visible to others. For tasks this also works when syncing. E.g. Kontact and davdroid only sync the non-private tasks and show no content for confidential tasks. The task app should respect those settings as well.

**Comment by sahne123** [comment]
I just had a look at the problem with privacy settings. Private Tasks should be hidden, that's obvious. Later we should implement this setting also in the frontend. But What's the best way to handle confidential Tasks? Should those tasks be shown at all? Can't imagine a useful scenarios for knowing there is a task without any other information.

**Comment by sahne123** [comment]
I've checked the other problem. The good part: permissions (readonly/add/edit/delete) are all fine in the backend. Also in combination with private or confidential Tasks.

What we have to do: Fix is the frontend. For users it seems like they can edit tasks but these values will never be stored and are lost after reloading the page. We have to disable forms depending on user permissions. At this point we should also discuss #169

**Comment by sahne123** [comment]
I've started implement permission checks. There is much to do. Since it's possible there are only read only calendars we may also have no default list with create-permission at all. This case is a problem in the calendar app as well (maybe fixed in the rework branch, didn't check).

As soon i have a some implementations, i will create a pull request, so you can join.

**Comment by raimund-schluessler** [comment]
This should be fixed in master now. Please report if something still does not work as expected.
