### ISSUE TITLE
App does not provide an info.xml file

### ISSUE THREAD

**Issue by nodiscc** [owncloud/tasks#114]
Hi, I've been trying to install this app on Owncloud 7.0.4 on Debian (from the "+ Apps" menu item). The install fails with the following message: `App does not provide an info.xml file`. Would you know how to fix this?

Thanks

**Comment by groovetemple** [comment]
I have the same issue.. Any insight would be appreciated.  Thank you!

**Comment by nodiscc** [comment]
@raimund-schluessler ping. Do you have any clue?

**Comment by nodiscc** [comment]
I found that

1) The Tasks app is marked as being a "placeholder for future updates" in the app list.
2) There are many complaints about the way the Owncloud app store works, and developers seem to prefer using git for app hosting.
3) The Tasks app works perfectly when installed by cloning this repo in the `apps/` directory of my owncloud installation.

So I'll close this issue. @raimund-schluessler It would be great that you update your README with short installation instructions (clone this repository or download and extract the zip in your apps directory). I advise that you also remove the Tasks app from the OC app store since it doesn't work from there and users will just assume it's broken. Thanks

**Comment by raimund-schluessler** [comment]
Sorry that I didn't answer faster, I just don't have to much time at my hands at the moment.

The app which is installed by the apps menu is https://apps.owncloud.com/content/show.php/Tasks?content=166058 which I didn't place in the app store, so I cannot remove it. The correct app in the app store would be https://apps.owncloud.com/content/show.php/Tasks?content=164356 but it is apparently not shown in the apps menu. I will try to figure out why this placeholder is in the app store and maybe the apps menu could point to the correct app then.

In the meantime you have to install the app manually by downloading it either from Github or from the app store.

Regards.
