### ISSUE TITLE
Allow configuration of default screen

### ISSUE THREAD

**Issue by djibux** [owncloud/tasks#116]
I would like the app to open on the "Today" view.  I am sure people prefer other views by default.  I think this should be a configuration setting.

**Comment by raimund-schluessler** [comment]
I am not sure, if this really deserves a configuration option.

First option you have is to set a bookmark to the today view.

Or, if you really want to always open it on today view, you could edit https://github.com/owncloud/tasks/blob/master/js/public/app.js#L23 from `redirectTo: '/lists/all' ` to `redirectTo: '/lists/today'` which should do the trick.

**Comment by djibux** [comment]
Second option works for me thanks.  I am just afraid I will have to apply the patch on each release.

**Comment by raimund-schluessler** [comment]
Yes, for now you will have to do it with each release. But as you have to upgrade the app manually anyway, changing one line of code should not take to much additional time.

**Comment by djibux** [comment]
You are right.  Thanks.
