### ISSUE TITLE
Implement owncloud search

### ISSUE THREAD

**Issue by raimund-schluessler** [owncloud/tasks#120]
The app should implement a SearchProvider, so that the global owncloud search also finds tasks. The search should also find completed tasks, which need to be loaded when they are clicked in the search results.

**Comment by raimund-schluessler** [comment]
@alfish2000 Have a look at https://github.com/owncloud/tasks/tree/Global-Search for a first implementation of global search for the tasks app.

Still todo:
- [ ] make search results app specific (requires oc8) https://github.com/owncloud/core/pull/12555
- [ ] load tasks which are not loaded inside the app (global search finds tasks which may not be loaded inside the app as they have been completed long ago)
- [ ] sort search resuls by date / completed or what-ever

**Comment by alfish2000** [comment]
Ok. I'll have a look at the Global OC Search implementation asap (maybe today at the late afternoon I could provide some feedback)
And please see also my comment about keeping the internal search here #122 
Thanks.

**Comment by alfish2000** [comment]
I've tested the Global OC Search quickly.
It works fine so far.
I only noticed one difference compared to the internal search:
The Internal Search finds matches in task comments and the Global Search not.

**Comment by raimund-schluessler** [comment]
Yes, you are right, comments are not searched yet. I will add this.

**Comment by alfish2000** [comment]
Thanks.
Global OC Search in comments is working now.
Found another thing:
The Global OC Search shows completed tasks too.
But when clicking on the completed task, the task is not found.
I think the problem is the URL.
In the OC Search dropdown the URL of the completed task is:
owncloud/index.php/apps/tasks/#/lists/3/tasks/11
But the completed task has this URL in the tasks app:
owncloud/index.php/apps/tasks/#/lists/completed/tasks/11

**Comment by raimund-schluessler** [comment]
The URL should be fine. The point is that the apps doesnt load all completed tasks as to many tasks slow it down a lot. So the task is not there at all. With 00317d84fb33cd7d8239f1d1914b8d8765625ae7 this should be solved. Did you test with the latest version of the GlobalSearch branch?

**Comment by alfish2000** [comment]
Found a second search relevant issue:
I'm using the Mirakel app on Android and sync with davdroid to OC.
In Mirakel I can add tags to the tasks. e.g. Movies and Drama (to tag all Drama Movies releated tasks)
The tags are stored in the "calendardata" column of the DB as:
...
CATEGORIES:Movies
CATEGORIES:Drama
...
Now the search also finds these tags.
Which is really nice.
But when opening the task details, the tags are not shown anywhere.
Do you plan to make Tags available in the UI e.g in the list view and/or the detailed view.
Maybe to display them only in the first place and later make them editable too.
A related issue seems to be #30

**Comment by alfish2000** [comment]
I've made a git pull of the Global-Search branch right now.
The completed task is already loaded and visible in the APP under the URL:
owncloud/index.php/apps/tasks/#/lists/completed/tasks/11

**Comment by raimund-schluessler** [comment]
Then it should also be there in the respective calendar/list as the "completed" list as basically a filter for all tasks. Can you have a look to which calendar this task actually belongs and check if you find it there too?

**Comment by raimund-schluessler** [comment]
Categories are searched as the implementation was quite easy. In principle it shouldnt be too hard to show and edit categories inside the app too, but at the moment I am not working on this.

**Comment by alfish2000** [comment]
Ok. After loading further completed tasks, the completed task was in its previous list and the link from Global OC search worked.
So it seems to be fine.

**Comment by raimund-schluessler** [comment]
Does it also work when you dont load anything from hand? And is it shown in list 3 when you see it in list completed?
When you load the app and search for this task it should be either already there, so nothing is loaded, or it should be loaded automatically by the app.
Thanks for your feedback!

**Comment by alfish2000** [comment]
This is what I can observe:
- To be sure that nothing is cached I've started Chrome browser (used Firefox before)
- Open the Tasks app
- Use the App internal search
- It finds the active task, the second already completed task is not shown
- Use the Gobal search
- The dropdown shows 2 tasks
- Clicking on the completed task in the dropdown shows "Task not found" in the detailed task panel.
- Now I click "load remaining completed tasks" on the list which contains the completed task
- Use the App iinternal seach again
- Both tasks are shown now
- Use the Global Search and click on the completed tasks in the dropdown
- Now the detailed task panel shows the completed task details correctly.

Just as a side note:
I noticed that when opening the internal Search in Chrome Browser by clicking the magnifier icon, the input focus is set to the search field automatically.
In firefox the focus is not set as I wrote in #122 
So there seems to be some browser difference there.

**Comment by raimund-schluessler** [comment]
Hm, this is odd. The app should load the task automatically (basically what you are triggering with "load remaining completed tasks" but only for the single tasks which was searched). I have not explanation right now for this. Thanks for the detailed report.

**Comment by alfish2000** [comment]
You mean the app should load a completed task when selecting it in the Global OC Search dropdown?
Btw I'm still using OC 7.0.4

**Comment by raimund-schluessler** [comment]
Yes, thats what I mean. I implemented this with https://github.com/owncloud/tasks/commit/00317d84fb33cd7d8239f1d1914b8d8765625ae7 and at least for me it works here (on OC 7.0.4).

**Comment by alfish2000** [comment]
I've debugged a little (app.js in firefox script debugger) and it seems that "loadTask" is never called for me:
...
              return _tasksbusinesslayer.getTask(_$scope.route.taskID, function(data) {
                return _$scope.loadTask(_$scope.route.taskID);
...
getTask is called but a breakpoint in loadTask is never hit:
...
          this._$scope.loadTask = function(taskID) {
...

**Comment by raimund-schluessler** [comment]
Do you see a request to ```owncloud/index.php/apps/tasks/task/{taskID}``` when clicking on the search result for a task not available/loaded in the app?

**Comment by alfish2000** [comment]
This Url was visible in the browser URL field.
I also could see a "Loading" message and the round rotating icon in the details view.
But then "Task not found" was shown in the details view.
I did not look at the "network" part of Firefox debugging tools.
And I cannot replay that because I have upgraded to OC 8.0.
BTW is there a special git branch I should use to help testing?

**Comment by raimund-schluessler** [comment]
The master branch inlcudes support for oC8 and also the global search. So please use this branch to test again if the issue persists.

**Comment by alfish2000** [comment]
Ok. I have used the master branch but the Global Search does not find anything.
It just displays the same tasks in the main panel as before the search.
And then below that there are also no hits in other locations.
Maybe the update of OC did not work properly.
But I dont find any error messages anywhere.

**Comment by raimund-schluessler** [comment]
The tasks which are already loaded inside the app are not filtered yet. But below them there should appear a panel with "No results in other places" or "XX results in other places" where all tasks matching the query should appear.

The fact, that it doesn't find any tasks is weird, because I didn't change anything of the search logic, there were visual fixes for oC8.

**Comment by alfish2000** [comment]
I've installed a new test environment in xampp to start freshly without any upgrade in between.
I've downloaded the 8.0 OC zip and installed it.
The first problem was, that there were no "recommended apps" at all and I could not install the calendar app via admin UI.
I've installed calendar via git then.
Then I've installed Tasks app.
I really could see some tasks matches in "other places" then when searching in global OC.
When clicking on them, the list they are contained opened.
The global search seems to be buggy in general in OC (or is it just working in the files app at all?)
I was expecting to find e.g. the file "example.odt" when searching for "exam" in tasks.
And I expected to find a task when searching for a task in the files app.
But neither way worked properly.
And on my linux installation the OC global search in tasks is not working (in files app it works)
I never see the "searching in other places" circular icon and I get no hits in the tasks app.
And I tried to debug via firefox script debugger again.
But I cannot figure out how to properly debug that scripting stuff.
I dont get any error log entries anywhere and I cannot figure out how to traces the call sequence in order to check why it works a little better in xampp on windows as it does in native linux.

**Comment by raimund-schluessler** [comment]
The global search in oC8 only searches in the respective app. So searching in the files app for a task won't show the task and searching for a file in the tasks app won't show the file. This is the expected behaviour since oc8.

I haven't tested the global search on my linux server yet, only on my XAMPP development installation. I am currently implementing the filter to only show tasks which match the query in the current view. When this is done I will filter all tasks which are already shown to not show in the global search results.

When this is done I will test on Linux, maybe I will find the reason why it's not working for you.

**Comment by raimund-schluessler** [comment]
Search should work as expected now. There are still some tweaks which could be integrated (such as making tasks found by the search behave the same as normal tasks) but this would require changes on the owncloud search implementation in core I guess.

@alfish2000 could you test it please.

**Comment by alfish2000** [comment]
Seems to be fine after some quick tests.
The white area under the search results is gone now and everything looks nice so far.

**Comment by raimund-schluessler** [comment]
@alfish2000 I found an issue that normal users (non admins) were not allowed to load a task when clicking on a search result. This was fixed with d75353a45b7b2bcbe8d91423b0de587d9631b32f. Probably this was the reason for one of your issues.

**Comment by alfish2000** [comment]
Yes.
That could be possible.
I cannot reproduce that old error I had to check your fix now.
But it seems reasonable that getTask($taskID) should be callable by non-admins too.

BTW
I've started reading a little about AngularJS to see how all that client side javascript is working.
And I've made some progress with handling CATEGORIES (tags support)
I've used https://mbenford.github.io/ngTagsInput/ to display and modify tags.
I got it integrated in the detailed view of a tasks.
But I had problems to find a good way to update the tags from database and when to write them back.
Just made a quick and dirty hack and connected storing the CATEGORIES when task.note is modified. I saw there is some kind of 5sec watcher for that task.note.
Better would be to use some feature of ngTagsInput to detect when it is "dirty" to save it then.
Well, I'm just making the first steps with AngularJS :-)

**Comment by raimund-schluessler** [comment]
Sounds good. That's the way I had in mind regarding categories. There also is already an issue for supporting categories, see #30. Let's discuss the implementation there.

Tags should be updated, when changed. I think a watcher should not be necessary. ngTagsInput looks promising, though. Support of categories could be implemented for Tasks v0.7.
