### ISSUE TITLE
Set input focus to search field

### ISSUE THREAD

**Issue by alfish2000** [owncloud/tasks#122]
A little improvement could be to set the input focus to the search field when opening the search by clicking on the magnifier icon.
Currently I have to click the magnifier to open the search field and then have to click in the search field so that it gets the focus to be able to type in.

**Comment by raimund-schluessler** [comment]
I plan on merging the in-app filter into the global oc search, so this should be unnecessary then.

**Comment by alfish2000** [comment]
I use the App internal search as some kind of filter which shows only tasks containing the search term as a task list in the main panel.
Can the "Global OC Search" offer the same?
The "Global Search" looks like just displaying a dropdown under the global search field.
So please keep the internal Search for some kind of filtered view.
And the global search could find some single tasks.
Or am I wrong with my assumptions about the global OC search?

**Comment by raimund-schluessler** [comment]
At them moment the Global search is not able to filter inside the app. But with oC8 this will be implemented for the files app. So if you search something with the global search, it shows you all results for the current app and also other apps as files or calendars in the dropdown menu. But also, it filters the results shown inside the current app (just as the internal task search would currently).

This means you should not lose any functionality with moving to the global search.

**Comment by alfish2000** [comment]
Ah Ok.
Thanks for clarifying that topic.

**Comment by raimund-schluessler** [comment]
The tasks are now filtered within the app when typing into the global search bar. Hence, I removed the search field of the app with 6a82d7761f03f4360d825f44ca685814067b2fdb.

**Comment by alfish2000** [comment]
I've tested the new global search (from master branch) only very quickly.
It seems to work fine so far.
I'll do some more tests during the next days and report any problems.

**Comment by raimund-schluessler** [comment]
Thanks! Global search is nearly finished. Only visual fixes planned so far (see status on #120). I will test it on my LAMPP server afterwards, then it should be ready to go.
