### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by alfish2000** [owncloud/tasks#123]
I think more keyboard shortcuts could be useful in general.
E.g. for opening the search field (e.g. Strg-F or something like that)
Currently the search already can be closed with ESC which is nice.
So it would be even nicer if it could be opened by keyboard too.

**Comment by raimund-schluessler** [comment]
Thanks for the suggestion, but closing as it is a duplication of https://github.com/owncloud/tasks/issues/23

**Comment by alfish2000** [comment]
Oh. Sorry. Didn't search for that issue before :-)
If added my "Strg-F" proposal as comment to #23
