### ISSUE TITLE
backup/export/sync for offline use?

### ISSUE THREAD

**Issue by nodiscc** [owncloud/tasks#124]
How am I supposed to synchronize my tasks to a local file in some way? There is no documenatation on how to do this. Any local/offline-available storage backend is fine. Is this even possible?

**Comment by nodiscc** [comment]
@raimund-schluessler I just realized that syncing was available through CalDav and that task lists were linked to owncloud's calendars. Would you add that to the README? Currently it's empty and needs a few words on usage (sync) and installation instructions.

**Comment by raimund-schluessler** [comment]
Yes, the tasks are synced by CalDAV just like all other calendar entries. An export is not included in the tasks app, but it is inside the calendar app (download the respective calendar). So I guess there is no need to implement this inside the tasks app as well.

Readme  could need some additions, though :) https://github.com/owncloud/tasks/issues/125
