### ISSUE TITLE
Syncing with calendar don't shows events.

### ISSUE THREAD

**Issue by masakkre** [owncloud/tasks#127]
Well, first of all, Thank You for this great job. I am assembling an Owncloud server and this app it is just what I need for it!! I was looking for a forum to put this, but I can't find it. I don't konw if I am doing this in the right place so, if it isn't, I am sorry :)

And now, my little troubles ;P

1- I am having some problem with the syncing with the calendar. I can see all my calendars at task-manager, I can create new calendars from the task-manager, but when I create a new event on the calendar, it doesn't appears at task-manager. And if I create a new event at task-manager, it doesn't shows at my calendar.

2- Is there any way to attach a document to the entrys at task-manager?

this is my server config:
Ubuntu server 14.04
Mysql 
Owncloud 7.0.4 (from owncloud repositorys)
task-manager 0.5.0 (actual version)

The only thing I changed in the task-manager its the folder name to tasks. Perhaps it could be some config to do??

Thank you again ;)

**Comment by raimund-schluessler** [comment]
1) Events in calendar and tasks in the task-app are stored as different entries in the database (VEVENT and VTODO respectively). So they don't show up in the other app. There is already an issue for showing tasks with start and end date in the calendar (see https://github.com/owncloud/tasks/issues/19) but showing calendar events in the task app doesn't make sense.

2) There is currently no way of attaching files to a task or event, although this would be useful and possible. Issue for this is https://github.com/owncloud/tasks/issues/9.

So there is nothing wrong with your config, it just isn't supported yet.
