### ISSUE TITLE
Task not found!

### ISSUE THREAD

**Issue by schoenf** [owncloud/tasks#131]
After having upgraded from ownCloud 7 to ownCloud 8, my tasks are visible but when clicking on them, "Task not found!" appears in the right part of the window not having any buttons or edit boxes to edit the tasks.

Even new added tasks show "Task not found!"

owncloud.log does not show any error. The behaviour persists even after deinstallation and reinstallation of ownCloud 8 with installation of tasks 0.5 via git clone.

**Comment by raimund-schluessler** [comment]
Tasks isn't really tested with oC8 and the support for oC8 is only rudimentary yet.
That been said, could you please give a little more detail about your setup (e.g. which database, version of the calendar app, master branch of tasks?)?

And which URL is shown when you click on a task?

**Comment by schoenf** [comment]
Database is mysql:
mysql  Ver 14.14 Distrib 5.1.73, for redhat-linux-gnu (x86_64) using readline 5.1

Calendar: 0.6.4

Tasks: 0.5

When I enter the app, the URL is
https://secure.##########.de/owncloud/index.php/apps/tasks/#/lists/all

When clicking on a task, the URL changes to
https://secure..##########.de/owncloud/index.php/apps/tasks/#/lists/all/tasks/1281
(the number at the end changes for different tasks.)

I can find the task via the ID in the mysql database. There the content of "calendardata" is:

BEGIN:VCALENDAR
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Europe/Berlin
X-LIC-LOCATION:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
END:STANDARD
END:VTIMEZONE
BEGIN:VTODO
CREATED:20141129T135933Z
LAST-MODIFIED:20150110T215223Z
DTSTAMP:20150110T215223Z
UID:c53421b9-7fbe-4bee-9540-3917df53fa7a
SUMMARY:################
STATUS:IN-PROCESS
DUE;TZID=Europe/Berlin:20150115T183000
PERCENT-COMPLETE:25
SEQUENCE:4
X-MOZ-GENERATION:3
END:VTODO
END:VCALENDAR

(all personal information replaced with ####)

**Comment by raimund-schluessler** [comment]
Hm, "Task not found!" is only shown when ```TaskState()``` at https://github.com/owncloud/tasks/blob/master/js/app/controllers/detailscontroller.coffee#L86-L93 returns ```null```. This only happens when ```_$tasksmodel.getById(_$scope.route.taskID)``` at https://github.com/owncloud/tasks/blob/master/js/app/controllers/detailscontroller.coffee#L40 doesn't return a task. But this should not happen as your tasks are shown and are therefore present in the model. I don't have an idea right now, but will try to have a look in the evening.

**Comment by schoenf** [comment]
So strange! I changed nothing ... and even did not log out and in again. But the problem is gone and the tasks are editable. No idea what the problem was! You can close the ticket!

**Comment by schoenf** [comment]
Probably a digilent oC cronjob fixed something ...

**Comment by raimund-schluessler** [comment]
Strange indeed. Reopen the issue if necessary.
