### ISSUE TITLE
Tasks 0.5 UI errors

### ISSUE THREAD

**Issue by koehn** [owncloud/tasks#132]
Tasks 0.5, OwnCloud 8.0.0-5, Ubuntu 14.04, Apache 2

When I load the page in Firefox 35 or Safari iOS 8, I get the following error:
`TypeError: moment.locale is not a function js.js:1027`

Looking at the Network log, it's loading moment-with-locales.js but *not* moment.js. 

HTML document includes (all script tags prior to `js.js`)
````
							<script type="text/javascript" src="/index.php/core/js/oc.js?v=f7ae3e9a65796be790ea58008ffd6386"></script>
					<script type="text/javascript" src="/core/vendor/jquery/jquery.min.js?v=f7ae3e9a65796be790ea58008ffd6386"></script>
					<script type="text/javascript" src="/core/vendor/jquery/jquery-migrate.min.js?v=f7ae3e9a65796be790ea58008ffd6386"></script>
					<script type="text/javascript" src="/core/vendor/jquery-ui/ui/jquery-ui.custom.js?v=f7ae3e9a65796be790ea58008ffd6386"></script>
					<script type="text/javascript" src="/core/vendor/underscore/underscore.js?v=f7ae3e9a65796be790ea58008ffd6386"></script>
					<script type="text/javascript" src="/core/vendor/moment/min/moment-with-locales.js?v=f7ae3e9a65796be790ea58008ffd6386"></script>
					<script type="text/javascript" src="/core/vendor/handlebars/handlebars.js?v=f7ae3e9a65796be790ea58008ffd6386"></script>
					<script type="text/javascript" src="/core/js/placeholders.js?v=f7ae3e9a65796be790ea58008ffd6386"></script>
					<script type="text/javascript" src="/core/js/jquery-tipsy.js?v=f7ae3e9a65796be790ea58008ffd6386"></script>
					<script type="text/javascript" src="/core/js/compatibility.js?v=f7ae3e9a65796be790ea58008ffd6386"></script>
					<script type="text/javascript" src="/core/js/jquery.ocdialog.js?v=f7ae3e9a65796be790ea58008ffd6386"></script>
					<script type="text/javascript" src="/core/js/oc-dialogs.js?v=f7ae3e9a65796be790ea58008ffd6386"></script>
					<script type="text/javascript" src="/core/js/js.js?v=f7ae3e9a65796be790ea58008ffd6386"></script>
````

I cannot render the Tasks App UI at all. Other apps work as expected.

**Comment by raimund-schluessler** [comment]
Thanks for the report. Problem is that owncloud now loads its own version of ```moment.js``` which is newer than the one used by the task app (where ```moment.locale`` is not available, hence the error). You can use the stable8 branch or the current master, where the bug is solved and a lot of layout glitches under oC8 are fixed.

However, the tasks app isn't really tested under oC8 yet and some things may or may not work (although no data will be corrupted so you are welcome to test).

**Comment by koehn** [comment]
This works, but I don't think the issue should be closed. The app should either be updated to be compatible with the current version of owncloud, or pulled from the list of apps.

**Comment by raimund-schluessler** [comment]
The issue is closed for master, hence it can be closed here. Releasing an update to apps.owncloud.com is another thing. And I didn't state anywhere in the description that it is compatible with oC8.

**Comment by enoch85** [comment]
@raimund-schluessler Off topic: when will you update the app? Running git-master now and it works great.

**Comment by raimund-schluessler** [comment]
I plan on integrating the global search into the app and it isn't quite finished for master. Also (but not only) because of https://github.com/owncloud/core/pull/13969. So I will release it when this is done. The app could probably also get an ocsid then, which should enable an automatic updating through the app store if I understand it correctly.

Btw: As it currently doesnt have an ocsid it shouldn't be visible on an "list of apps", which is why I don't really understand this issue here. You have to copy it manually to see it in the apps list (correct me if I am wrong, but at least for my test installation it behaves this way).

**Comment by enoch85** [comment]
@raimund-schluessler If you update from oC7 to oC8, the app remains in .../.../apps and is therefore visible in the apps menu.

**Comment by raimund-schluessler** [comment]
Yes it is, but that is nothing I could prevent by removing it from an "installable apps" list as desired in https://github.com/owncloud/core/issues/14063.

**Comment by enoch85** [comment]
@raimund-schluessler Yes, I know. This is not a bug.
