### ISSUE TITLE
OC8 - Fatal error: Class 'OC_Calendar_App' not found

### ISSUE THREAD

**Issue by j-ed** [owncloud/tasks#133]
## Actual behavior

After upgrading to OC8 and installing the latest tasks app v0.5 it couldn't be used anymore and
the following error is displayed:
```
Fatal error: Class 'OC_Calendar_App' not found in /var/www/htdocs/owncloud/apps2/tasks/controller/pagecontroller.php on line 46 
```

#### Server Configuration

OS: Linux 3.2.54
Web server: Apache2 2.4.10
Database: MySQL 5.1.73
PHP version: 5.4.35
ownCloud version: 8.0.0
Tasks App version: 0.5

#### Client Configuration

Browser: Firefox 35.0.1
Operating system: Windows 7

**Comment by raimund-schluessler** [comment]
This looks like the calendar app is not enabled or can't be found (probalby due to your custom apps directory ```apps2```. Please check that the calendar app is working correctly. You also have to use the latest master of the tasks app, but I guess you already do so.

**Comment by raimund-schluessler** [comment]
Addition: From the line count of the error message I think you are still using the stable7 branch. This should not cause the issue you are having here, but will cause other problems within the javascript code on the client side. So you actually have two problems ;)

**Comment by j-ed** [comment]
I had downloaded the tasks app v0.5 from the app store and installed it at first and indeed the calendar app was missing because it hasn't be shipped with the OC8 build anymore.
It might be worse to check if the calendar app has been installed to prevent error messages.
After installing the calendar app the error message wasn't shown anymore but the tasks app still refuses to work. An empty page was shown.
:+1: After I've downloaded and installed the task app v0.5 from master all problems have vanished and the app is working as expected again. It might be worse to update the app in the app store asap ;-)

**Comment by raimund-schluessler** [comment]
I actually do check if the calendar app is enabled. I guess it was enabled (marked in the oc database as enabled) but wasn't there in the filesystem. I don't know it it is possible to check for this.

I do plan to update the app in the app store, but I haven't tested it enough yet.
