### ISSUE TITLE
Add ocsid

### ISSUE THREAD

**Issue by raimund-schluessler** [owncloud/tasks#136]
Should the tasks app get an ocsid so it is updateable via app store?
Are the ocsid under https://gist.github.com/georgehrke/04d7aff69938989f9a13 still valid? Or is the correct ocsid ```164356``` from https://apps.owncloud.com/content/show.php/Tasks?content=164356?

This could be done once it is ready for oC8.

Also probably the dummy app under https://apps.owncloud.com/content/show.php/Tasks?content=166058 should be removed then?

**Comment by raimund-schluessler** [comment]
Also see https://github.com/owncloud/core/issues/14063 and https://github.com/owncloud/tasks/issues/132#issuecomment-73802341.

**Comment by enoch85** [comment]
CC @DeepDiver1975 (?)

**Comment by karlitschek** [comment]
Hmmm. Not sure. Actually if the tasks app is installed via the appstore than it should get updates independently if it has an ocsid configured or not. This should only make a difference if you install it via git which is not the correct way for endusers
