### ISSUE TITLE
STATUS:COMPLETED missing in VTODO

### ISSUE THREAD

**Issue by alfish2000** [owncloud/tasks#137]
It seems that STATUS:COMPLETED is missing in VTODO database entry when a task is set to completed in tasks app.
I have synced with 2 clients ("Mirakel" on Android and "eM Client" on Windows) and both show the tasks as not completed but Tasks App shows it as completed.
If I add STATUS:COMPLETED to the database entries by hand in the vcalendardata it is synced correctly to the clients and both show the task as completed.
So I think the Tasks App should set STATUS:COMPLETED too.
Tested with:
- 7.0.4 and Tasks "Global-Search branch".
- 8.0 (stable) and Tasks 0.5.1

**Comment by raimund-schluessler** [comment]
Hm, Thunderbird/Lightning and iOS never complained about this.

I will include this fix in the next release.

**Comment by alfish2000** [comment]
I've tweaked the source a little and this seems to work fine:

	controller/taskscontroller.php | 2 ++
	1 file changed, 2 insertions(+)
	
	diff --git a/controller/taskscontroller.php b/controller/taskscontroller.php
	index 83ec1c6..a4e6468 100644
	--- a/controller/taskscontroller.php
	+++ b/controller/taskscontroller.php
	@@ -225,8 +225,10 @@ class TasksController extends Controller {
					$timezone = new \DateTimeZone($timezone);
					$isCompleted = new \DateTime($isCompleted, $timezone);
					$vtodo->setDateTime('COMPLETED', $isCompleted);
	+				$vtodo->setString('STATUS', 'COMPLETED');
				} else {
					unset($vtodo->COMPLETED);
	+				$vtodo->setString('STATUS', 'NEEDS-ACTION');
				}
				\OC_Calendar_Object::edit($taskId, $vcalendar->serialize());
			} catch(\Exception $e) {

**Comment by raimund-schluessler** [comment]
Thanks for your effort. I will try to have a look tomorrow.

**Comment by raimund-schluessler** [comment]
Sorry for the delay, I don't know if can have a look before the weekend.
