### ISSUE TITLE
Fails to Load Under Linux Firefox

### ISSUE THREAD

**Issue by jalcine** [owncloud/tasks#141]
This happened constanty to no avail. Snapshots below.

![snapshot33](https://cloud.githubusercontent.com/assets/452100/6263198/1f6f4e76-b7e1-11e4-928d-e173de8ee8ba.png)

**unsafe-eval** is what's it's complaining.

![snapshot33](https://cloud.githubusercontent.com/assets/452100/6263191/fc59085a-b7e0-11e4-9028-8126bfefdc76.png)

Any tips on how to fix this?

**Comment by raimund-schluessler** [comment]
The unsafe-eval ist not the problem, ```moment.locale is not a function``` is it.

You upgraded to oC8 and still use Tasks 0.5 I guess. Use the current master or stable8 branch and the problem should be gone, see https://github.com/owncloud/tasks/issues/132 for details.

**Comment by jalcine** [comment]
Actually a new member of the ownCloud group :grin: But thanks for that heads up. Maybe a compability page on the Wiki would help? Seems like you guys are almost there wth support anyway.

**Comment by raimund-schluessler** [comment]
Yes I should add a hint on which version to use. I will do so for the next release.
