### ISSUE TITLE
Task edition is broken on mobile devices

### ISSUE THREAD

**Issue by djibux** [owncloud/tasks#143]
On mobile devices, the edit screen does not show up when selecting a task.
(The screen must be at least 769 pixels wide)
![2015-02-25 09_34_37-taches - owncloud](https://cloud.githubusercontent.com/assets/6897338/6367329/f7c0f028-bcd1-11e4-94ef-22d9765d71b2.png)
![2015-02-25 09_36_01-taches - owncloud](https://cloud.githubusercontent.com/assets/6897338/6367331/f97704ac-bcd1-11e4-9bc4-05748ab83f3a.png)

**Comment by raimund-schluessler** [comment]
Thanks for the report, should be fine now.
