### ISSUE TITLE
PHP errors - not respecting api

### ISSUE THREAD

**Issue by strayobject** [owncloud/tasks#144]
Using Task app v0.5 n OCv7.0.4

>Argument 5 passed to OCA\Tasks\Controller\CollectionsController::__construct() must be an instance of OCA\Tasks\Controller\IConfig, instance of OC\AllConfig given, called in [...]/apps/tasks/appinfo/application.php on line 61 and defined at [...]/apps/tasks/controller/collectionscontroller.php#35 

>Argument 2 passed to OCA\Tasks\Controller\TasksController::__construct() must be an instance of OCA\Tasks\Controller\IRequest, instance of OC\AppFramework\Http\Request given, called in [...]/apps/tasks/appinfo/application.php on line 86 and defined at [...]/apps/tasks/controller/taskscontroller.php#34

**Comment by raimund-schluessler** [comment]
This is a dup of #104 and was fixed with https://github.com/owncloud/tasks/commit/277f2ee83dd7189534ba3d83b335211a6ce7abdf. Please use the current version from Github.

**Comment by strayobject** [comment]
Is 'current' a stable7 branch?
