### ISSUE TITLE
v0.5: Exception error in OC8

### ISSUE THREAD

**Issue by smiddy** [owncloud/tasks#150]
After upgrading my OC to 8.0.0 on my ubuntu 14.04 I get the following error in the logs when I want to access the task app:

`Exception: {"Message":"Unable to generate a URL for the named route \"tasks.page.index\" as such route does not exist.","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/route\/router.php(282): Symfony\\Component\\Routing\\Generator\\UrlGenerator->generate('tasks.page.inde...', Array, false)\n#1 \/var\/www\/owncloud\/lib\/private\/urlgenerator.php(42): OC\\Route\\Router->generate('tasks.page.inde...', Array)\n#2 \/var\/www\/owncloud\/lib\/private\/helper.php(112): OC\\URLGenerator->linkToRoute('tasks.page.inde...', Array)\n#3 \/var\/www\/owncloud\/lib\/public\/util.php(219): OC_Helper::linkToRoute('tasks.page.inde...', Array)\n#4 \/var\/www\/owncloud\/apps\/tasks\/appinfo\/app.php(32): OCP\\Util::linkToRoute('tasks.page.inde...')\n#5 \/var\/www\/owncloud\/lib\/private\/app.php(379): require('\/var\/www\/ownclo...')\n#6 \/var\/www\/owncloud\/settings\/ajax\/navigationdetect.php(9): OC_App::getAppNavigationEntries('tasks')\n#7 \/var\/www\/owncloud\/lib\/private\/route\/route.php(135) : runtime-created function(1): require_once('\/var\/www\/ownclo...')\n#8 [internal function]: __lambda_func(Array)\n#9 \/var\/www\/owncloud\/lib\/private\/route\/router.php(250): call_user_func('?lambda_2191', Array)\n#10 \/var\/www\/owncloud\/lib\/base.php(763): OC\\Route\\Router->match('\/settings\/ajax\/...')\n#11 \/var\/www\/owncloud\/index.php(36): OC::handleRequest()\n#12 {main}","File":"\/var\/www\/owncloud\/3rdparty\/symfony\/routing\/Symfony\/Component\/Routing\/Generator\/UrlGenerator.php","Line":134} `

**Comment by raimund-schluessler** [comment]
Please try again with the stable8 branch or even better with the latest master eb5d61b4a2cbc38f9ea1e410015e001ee6edb5bc. Regards.

**Comment by smiddy** [comment]
I have the latest stable 8.0.2 from opensuse reps installed and still no success

**Comment by raimund-schluessler** [comment]
Do you also use the latest master of the Tasks app? For me it is working fine with oC8.0.2.

**Comment by smiddy** [comment]
Yes, with the lates master it is working!
Thanks
Markus

**Comment by raimund-schluessler** [comment]
Thanks for the feedback.
