### ISSUE TITLE
[0.5.1] Tasks don't show up in their respective calendars

### ISSUE THREAD

**Issue by Cysioland** [owncloud/tasks#151]
When I add new Tasks project, it shows both in web Calendar and CalDAV. But after I add a task in that project, complete with beginning date, due date and even reminder, it doesn't show up, both in Calendar and CalDAV.

**Comment by vdbjimmy** [comment]
Hello, same problem here. I expected to get something in the owncloud calendar when creating a new task with at least a due date. But nothing in the calendar.

**Comment by raimund-schluessler** [comment]
Showing tasks with date and time in the calendar is not yet supported. This needs changes in the calendar app. However, tasks do show up via CalDAV but your client has to support it (e.g. Thunderbird with Lightning or CalDAV Sync with additional Tasks app on Android, iOS shows tasks without additional software via CalDAV). Progress is already tracked in #19.
