### ISSUE TITLE
Make links clickable in tasks list

### ISSUE THREAD

**Issue by k0lter** [owncloud/tasks#154]
It could be very comfortable if the URIs (https?://, ftps://?, ircs?://, etc.) present in task content could be converted by clickable links.

Thanks.

**Comment by raimund-schluessler** [comment]
What do you mean with "task content"? Links in the note of a task a already parsed as you suggest.

**Comment by k0lter** [comment]
Sorry, I mean the task title.

**Comment by raimund-schluessler** [comment]
Closing in favor of #252 as comments are mentioned there too.
