### ISSUE TITLE
Import/Export task CSV, iCalendar...

### ISSUE THREAD

**Issue by kepon85** [owncloud/tasks#156]
Hello,

This plugin is almost perfect. missing only function Import/Export task CSV, iCalendar... (for migration)

Thank's

**Comment by kepon85** [comment]
Ok thank's !

**Comment by agilob** [comment]
I can't find this options. Was it removed?

**Comment by raimund-schluessler** [comment]
It is still present, though not in the Tasks app, but in the Calendar app as written above.

**Comment by agilob** [comment]
I can't find the option in the calendar

**Comment by raimund-schluessler** [comment]
![calendar](https://cloud.githubusercontent.com/assets/2496460/10147639/756db446-662f-11e5-842a-585a15dae68b.png)

**Comment by agilob** [comment]
That doesn't include importing.

**Comment by raimund-schluessler** [comment]
See edited comment above. Afaik it only works with ics files.

**Comment by agilob** [comment]
OK, I opened #271
