### ISSUE TITLE
"Add an item in..." is active even for lists/calendars user can't wirite to

### ISSUE THREAD

**Issue by jacekss** [owncloud/tasks#162]
Adding action on such list/calendar is causing error:
"message":"Exception: {\"Message\":\"You do not have the permissions to add events to this calendar.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/tasks\\\/controller\\\/taskscontroller.php(295): OC_Calendar_Object::add('21', 'BEGIN:VCALENDAR...')\\n#1 [internal function]: OCA\\\\Tasks\\\\Controller\\\\TasksController->addTask()

and whole app hangs.

**Comment by raimund-schluessler** [comment]
Already reported in #108. Will hopefully be covered with #247.
