### ISSUE TITLE
Update Coffeescript/Javascript development readme

### ISSUE THREAD

**Issue by Henni** [owncloud/tasks#163]
Currently the readme for the coffeescript development is describing a compilation with 'make'.
But as there is a gruntfile there should be an explanation on which grunt commands to execute to get the compiled and concatenated public/app.js file.

Maybe the gruntfile has to be redone as well, but I'm not sure about that.

**Comment by raimund-schluessler** [comment]
@Henni Do you consider this done with the changes merged with https://github.com/owncloud/tasks/commit/c733b02eb6ca5046a7e102f0f848db451d51c599 ?

**Comment by Henni** [comment]
Yes I think this is done
