### ISSUE TITLE
Colour marker  driven priorities

### ISSUE THREAD

**Issue by hitam4450** [owncloud/tasks#165]
How about an colour driven system (markers ) of different priorities ?? e.g. red, yellow, green, blue, etc..   ???

Regards, hitam4450

**Comment by raimund-schluessler** [comment]
This could collide with the colors already used by the calendar where the task is in. This color is already used to show the percentage of which the task is finished. It may also not be very intuitive as you have to remember which color represents which priority.

Maybe you can prepare a Mockup of what you are thinking of exactly.

**Comment by raimund-schluessler** [comment]
Implemented with #199
