### ISSUE TITLE
Exporting task list onto mobile system

### ISSUE THREAD

**Issue by hitam4450** [owncloud/tasks#166]
How about exporting a task list onto a mobile (ANDROID) system???

Regards, hitam4450

**Comment by raimund-schluessler** [comment]
You can sync your tasks to any device which supports CalDAV, including iOS (native), Android (probably external Apps necessary), or your Laptop running Thunderbird/Lightning etc.

You can also export all tasks by exporting the respective calendar ind the ownCloud calendar app.
