### ISSUE TITLE
Suggest to seperate "edit" privileges from commenting feature

### ISSUE THREAD

**Issue by Akuukis** [owncloud/tasks#169]
Right now we have "create", "edit" and "delete" privileges. I would like to have "create", "edit", "comment" and "delete" privileges. 

Reason: when I delegate (technically put in shared tasklist) a task, I would like only the target person to be able to edit the details and description of it. But in the same time I would like to let others see (possible by sharing without privileges) and join the discussion (by being able to comment) without ability to tinker with details and description.

**Comment by raimund-schluessler** [comment]
If this issue is still relevant, please reopen it in owncloud core as this takes care of all the CalDAV stuff now.
