### ISSUE TITLE
Adding a task doesn't work (freezes?)

### ISSUE THREAD

**Issue by DrDamnit** [owncloud/tasks#174]
Upgraded to OC 8.0.3 (Current), and installed this app, then realized it is "for the calendar" so installed the calendar. (Not sure if install order matters, but it might...).

I was able to create four new lists, A, B, C, and D. No problem.

When trying to add an item to any of the lists, (by clicking the "Add item" box, entering the item text, and then pressing enter) the added item freezes, but is not saved. Navigating away from that list (to another, for example) and then navigating back shows that the item was not saved, and the text box is now frozen.

Firebug shows that https://cloud.myserver.com/index.php/apps/tasks/tasks/add has generated an internal error (500). However, there is nothing in the Apache logs.

I have verified permissions. Everything appears to be fine. Please advise.

**Comment by raimund-schluessler** [comment]
Don't use the latest master of the tasks app, it is for oc8.1. See https://github.com/owncloud/tasks/issues/173
