### ISSUE TITLE
Error on Add Task

### ISSUE THREAD

**Issue by andrychuyko** [owncloud/tasks#175]
I enter task name and press enter 
sie do nothing
console report POST http://sync.stavsite.ru/index.php/apps/tasks/tasks/add 500 (Internal Server Error)
help me please

**Comment by Henni** [comment]
Hi @andrychuyko,
we will need a little more information.
Which version of owncloud and the tasks app are you using?

**Comment by sahne123** [comment]
same here: 

ownCloud 8.0.3 (stable) 
Tasks 0.6.0

**Comment by Henni** [comment]
The current master only works with owncloud 8.1 (see #173)
Please use [this stable release](https://github.com/owncloud/tasks/releases/tag/v0.6) for now.
Does this solve your problems @sahne123 @andrychuyko?

**Comment by sahne123** [comment]
Works like a charm. Thanks @Henni!
