### ISSUE TITLE
Changes RSS feed and maybe XMPP chatroom notifications?

### ISSUE THREAD

**Issue by poVoq** [owncloud/tasks#177]
Would be nice if there was an RSS feed included that would notify the users of new tasks and changes if a shared calender is used.

Great would be also if there was some way to push notifications to a XMPP chatroom.

**Comment by raimund-schluessler** [comment]
We could integrate the tasks app into the activity stream, but we have to implement proper support of shared calendars etc. first

**Comment by poVoq** [comment]
yes that would be also great as an rss feed option.
What is currently not working for shared calendars? I have been using the tasks without any problems using shared calendars...

**Comment by sahne123** [comment]
@poVoq see #108
