### ISSUE TITLE
Don't require time along with the date for Due and Start dates

### ISSUE THREAD

**Issue by mpeterson** [owncloud/tasks#18]
Sometimes you want to schedule a task for a particular day but not particular time

**Comment by korelstar** [comment]
The Android app OpenTasks has a checkbox "all-day" below of the fields for start and due, which disables the time-choser for both fields if activated. I like this approach and it could be realized here, too.

![screenshot_20160822-113211](https://cloud.githubusercontent.com/assets/6277619/17850228/87e7f692-685c-11e6-8790-b11d5f4e34b8.png)

**Comment by ccoenen** [comment]
Please double-check that we don't set off people's reminders at 0:00 at night, then :D

**Comment by korelstar** [comment]
God point. :-)
As far as I know, the tasks app ignores completely the `VALARM` property of a `VTODO`. Hence, reminders will not change.

However, the client app OpenTasks (Android) makes a notification at 0:00 at night if a all-day task is due/to be started on that day and notifications are activated in that app. But that's not in our hand and happens also, if ownCloud does not support the all-day feature.
