### ISSUE TITLE
No new Tasks

### ISSUE THREAD

**Issue by mitpro** [owncloud/tasks#180]
After updating oc and tasks no new tasks would be add to list.
Error in logs:

Exception: {"Message":"You must pass a \\Sabre\\VObject\\Component, \\Sabre\\VObject\\Property or scalar type","Code":0,"Trace":"#0 \/var\/www\/804\/apps\/tasks\/controller\/helper.php(231): Sabre\\VObject\\Component->__set('CREATED', Object(DateTime))\n#1 \/var\/www\/804\/apps\/tasks\/controller\/taskscontroller.php(294): OCA\\Tasks\\Controller\\Helper::createVCalendarFromRequest(Array)\n#2 [internal function]: OCA\\Tasks\\Controller\\TasksController->addTask()\n#3 \/var\/www\/804\/lib\/private\/appframework\/http\/dispatcher.php(158): call_user_func_array(Array, Array)\n#4 \/var\/www\/804\/lib\/private\/appframework\/http\/dispatcher.php(86): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Tasks\\Controller\\TasksController), 'addTask')\n#5 \/var\/www\/804\/lib\/private\/appframework\/app.php(97): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Tasks\\Controller\\TasksController), 'addTask')\n#6 \/var\/www\/804\/lib\/private\/appframework\/routing\/routeactionhandler.php(44): OC\\AppFramework\\App::main('TasksController', 'addTask', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#7 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#8 \/var\/www\/804\/lib\/private\/route\/router.php(252): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#9 \/var\/www\/804\/lib\/base.php(791): OC\\Route\\Router->match('\/apps\/tasks\/tas...')\n#10 \/var\/www\/804\/index.php(36): OC::handleRequest()\n#11 {main}","File":"\/var\/www\/804\/3rdparty\/sabre\/vobject\/lib\/Sabre\/VObject\/Component.php","Line":365}

**Comment by raimund-schluessler** [comment]
Please use the stable8 branch of the tasks app or download from https://apps.owncloud.com/content/show.php/Tasks?content=164356. The current master only works with oc8.1

Using the master branch is not the official practice to install apps.

**Comment by mitpro** [comment]
works well
