### ISSUE TITLE
[Feature request] Add general-purpose task collections

### ISSUE THREAD

**Issue by Pastafarianist** [owncloud/tasks#181]
Currently there are only a few collections available, all of which are predetermined. It would be extremely convenient to have an ability to add collections at any time, and organize task lists in a tree-like structure. The tree depth could be 1, but that still would simplify things if there were a lot of task lists.

**Comment by Henni** [comment]
There is already an issue for subtasks (see #49).
About the task collections: Are you looking for categories? We added them just a few days ago.
If you have suggestions maybe have a look over here #30.

**Comment by raimund-schluessler** [comment]
Adding new collections is not different from adding a new list, as it would appear in the list at the left. Since I think you don't want to see new entries in the left overview, but rather group associated tasks, I guess implementing subtasks is the way to go here.

I close this issue in favour of #49. Please reopen it if we got you wrong. Regards.

**Comment by Pastafarianist** [comment]
Thanks a lot for the update. Have the categories been included in any release, or are they still only in the repository?

**Comment by Pastafarianist** [comment]
Just to clarify, are those categories equivalent to folders? I should probably have used that word when I was opening the issue.

**Comment by raimund-schluessler** [comment]
No, they aren't. They are more like hash tags. So I guess they are not really what you look for. The implementation of subtasks I am thinking of is more like folders, but this is a big think to implement.

**Comment by Pastafarianist** [comment]
Well, then I should probably create a new issue with a more precise description. I'll get around to that.
