### ISSUE TITLE
Multiline task creation

### ISSUE THREAD

**Issue by kordianbruck** [owncloud/tasks#182]
Enable creating tasks using a text area. Each line should be create a single task. 

Similar behaviour can be found in a trello board.

**Comment by raimund-schluessler** [comment]
What is the benefit to adding them in an input field? You still have to type every task title and a linebreak after every entry, which means you don't save any time.

**Comment by Henni** [comment]
This would allow copy-pasting multiple tasks.

**Comment by raimund-schluessler** [comment]
Hm, but is this your regular work-flow to note your tasks in a separate file when you could just type them into the app directly?

**Comment by kordianbruck** [comment]
No, but the idea is that you get a shopping list from your mom and you want to save that into your tasks. Mom does not use ownCloud but rather relies on this old fashion, barely used technology called email. In order to import these a multi line c&p solution would be nice. Mom would also like this as I would then finally actually do the groceries properly without forgetting something.

**Comment by raimund-schluessler** [comment]
Ok, I got it ;)

I guess we could realize this, but we have to take care to not impere the user experience of people used to the standard input field.

**Comment by agilob** [comment]
+1

**Comment by agilob** [comment]
Will it be available in next update?
