### ISSUE TITLE
Change default settings to include/show all/important/completed

### ISSUE THREAD

**Issue by kordianbruck** [owncloud/tasks#184]
I think it would be somehow logical to display these by default in order to make the first usage by a user more intuitive.

**Comment by raimund-schluessler** [comment]
Actually this is the intended behaviour. If they don't show, it's a bug. But I must admit I didn't check for that as I have the app enabled since the first day ;)

**Comment by kordianbruck** [comment]
No in my current master checkout they didn't show...

**Comment by raimund-schluessler** [comment]
Ok, then we have to take a look at this.
