### ISSUE TITLE
Completed collection only shows 5 tasks per list

### ISSUE THREAD

**Issue by Henni** [owncloud/tasks#187]
![image](https://cloud.githubusercontent.com/assets/1267827/8214838/4d5a6962-152c-11e5-8742-f1ea5ac1b0bd.png)

**Comment by raimund-schluessler** [comment]
Do you really have more than 5 completed tasks per list? If you do, it should display an option to load the remaining tasks like so:

![unbenannt](https://cloud.githubusercontent.com/assets/2496460/8215893/702b0aee-1533-11e5-8b17-632527343ccc.jpg)

**Comment by Henni** [comment]
this only occurs if on every single list the completed tasks are hidden.

**Comment by raimund-schluessler** [comment]
Indeed, if they are hidden, the button is not shown. Shouldn't be to hard to fix.

**Comment by Henni** [comment]
Great thanks!
