### ISSUE TITLE
Don't use alerts to tell users about errors

### ISSUE THREAD

**Issue by kordianbruck** [owncloud/tasks#189]
![screenshot from 2015-06-17 21 19 18](https://cloud.githubusercontent.com/assets/298860/8216394/9fcb2c40-1536-11e5-85b2-59d28bae1346.png)

When creating a list that already exists this not so nice error message gets displayed. Is there something in the owncloud CI for error handling?

**Comment by sahne123** [comment]
The file app does it that way:

![2015-06-19 14_44_36-dateien - owncloud](https://cloud.githubusercontent.com/assets/1149152/8253582/9e4db3e0-1691-11e5-9756-e61962dcd3ac.png)

**Comment by Henni** [comment]
@jancborchardt is this the way to go? Didn't you say something about removing the tipsy in the long term?

**Comment by jancborchardt** [comment]
Yeah, this is the way to go. The discussion on tipsy was to replace it with Twitter Bootstrap’s version of tipsy: https://github.com/owncloud/core/issues/13646 (basically same thing, but more compatible)
