### ISSUE TITLE
Show tasks with time and date on the calendar

### ISSUE THREAD

**Issue by mpeterson** [owncloud/tasks#19]
When I have tasks with a scheduled time and a date I usually also want them to pop up on the calendar so I have that time allocated to do the task. 

Perhaps having a new field that can be filled with duration so if it's filled it will add the event on the calendar at the specified time and date.

**Comment by wobblywob** [comment]
I'm using todoist and Google Calendar to organize my time. If this would be implemented, it would be, IMO, the most complete time planning solution on the internet.

**Comment by jancborchardt** [comment]
@wobblywob are you a developer or have any developer friends who could help implementing this? Any contribution is welcome. :)

**Comment by SaerAlmukhlfi** [comment]
can you do it with a server side script ? , I mean to contact to the calendar app Via system side script
or you build up an api for  calendar (:

**Comment by georgehrke** [comment]
@SaerAlmukhlfi No, this should be done in JavaScript.

**Comment by georgehrke** [comment]
created an issue in the calendar app: https://github.com/owncloud/calendar/issues/499

**Comment by raimund-schluessler** [comment]
@georgehrke Thanks for creating the issue. I keep this issue here open until it is implemented in the calendar app (in case something has to be adjusted in the Tasks app).

**Comment by wobblywob** [comment]
@jancborchardt I'd love to help but I have no programming skills. I made the account just to comment on the project. I'd donate though, but I didn't see donation links.

**Comment by jancborchardt** [comment]
@wobblywob you can donate to specific issues using Bountysource. The money is only deducted from your account when the issue is successfully fixed. :)
- All issues of the Tasks app: https://www.bountysource.com/teams/owncloud/issues?tracker_ids=216529
- This specific issue: https://www.bountysource.com/issues/2163793-show-tasks-with-time-and-date-on-the-calendar
