### ISSUE TITLE
TypeError: moment.locale is not a function

### ISSUE THREAD

**Issue by aheusingfeld** [owncloud/tasks#190]
Whenever I open the tasks web app (v0.4) in my ownCloud 8.0.4 (stable) instance under `/owncloud/index.php/apps/tasks_enhanced/` in Firefox DevEdition 40.0a2, the above mentioned error message appears in the webconsole: `TypeError: moment.locale is not a function - js.js:1027:0`

This is the referenced piece of code:
```
	/**
	 * Set users locale to moment.js as soon as possible
	 */
	moment.locale(OC.getLocale());
```

The result is that only the owncloud navigation bar is displayed and the rest of the page stays blank. The navigation dropdown menu is not actionable anymore and you have to click on the owncloud logo to get back to the starting page.

**Comment by raimund-schluessler** [comment]
The reason is that oc8 brings moment.js on its own in other version than the tasks app. This is fixed in v0.6 of the tasks app, so please use the version tagged here: https://github.com/owncloud/tasks/releases/tag/v0.6
