### ISSUE TITLE
Task module

### ISSUE THREAD

**Issue by mnevens** [owncloud/tasks#192]
I installed the task module in ownCloud 8.0.4 (stable).
However I have a blank screen.
Could someone help me
Attached is a screenshot
![afbeelding 1](https://cloud.githubusercontent.com/assets/528547/8226822/68622558-15a2-11e5-8988-206f37426337.png)

**Comment by Henni** [comment]
Please use the [current stable release](https://github.com/owncloud/tasks/releases/tag/v0.6).
The current master only works with owncloud 8.1 (see #173)

**Comment by raimund-schluessler** [comment]
https://github.com/owncloud/tasks/issues/180
https://github.com/owncloud/tasks/issues/175

**Comment by raimund-schluessler** [comment]
I think we should add this to the readme. Somehow everybody is installing the development master branch on the stable core owncloud.

**Comment by Henni** [comment]
We should probably add that the installation via git is only for developers and link to the [latest release](https://github.com/owncloud/tasks/releases/latest) for everyone else.

**Comment by mnevens** [comment]
Hi, still have same problem.
I re-installed core 8.04 and tasks v0.6
Attached error report
![afbeelding 2](https://cloud.githubusercontent.com/assets/528547/8227684/9b2c2fcc-15a9-11e5-83a4-7fb8cf7b4e48.png)
