### ISSUE TITLE
Task module

### ISSUE THREAD

**Issue by mnevens** [owncloud/tasks#193]
Hi, still have same problem as issue #192 

![afbeelding 2](https://cloud.githubusercontent.com/assets/528547/8227784/37c64f70-15aa-11e5-9513-82af7b1d1628.png)

**Comment by Henni** [comment]
Are there still no tasks listed?
The error log describes a problem regarding adding tasks.

**Comment by mnevens** [comment]
I changed the rights to 777 in the tasks folder, and everthings is ok

**Comment by raimund-schluessler** [comment]
Thanks for the feedback, we probably should mention this too in the installation description.

**Comment by Henni** [comment]
@raimund-schluessler do you know why this is needed? Which files do we change inside of the tasks folder?

**Comment by raimund-schluessler** [comment]
Don't know. I guess it should work with the permissions ```rwxr-x—, or 0750``` like stated in https://doc.owncloud.org/server/7.0/admin_manual/installation/apps_management_installation.html#adding-third-party-apps too.
