### ISSUE TITLE
Split up the backend into services and controllers

### ISSUE THREAD

**Issue by Henni** [owncloud/tasks#196]
The [owncloud documentation](https://doc.owncloud.org/server/8.0/developer_manual/app/container.html) describes a MVC structure build out of services and controllers. Therefore the following files should be split up into two:
- [x] [taskscontroller.php](https://github.com/owncloud/tasks/blob/master/controller/taskscontroller.php)
- [x] [settingscontroller.php](https://github.com/owncloud/tasks/blob/master/controller/settingscontroller.php)
- [x] [listscontroller.php](https://github.com/owncloud/tasks/blob/master/controller/listscontroller.php)
- [x] [collectionscontroller.php](https://github.com/owncloud/tasks/blob/master/controller/collectionscontroller.php)

I don't think that [searchcontroller.php] (https://github.com/owncloud/tasks/blob/master/controller/searchcontroller.php) and [pagecontroller.php](https://github.com/owncloud/tasks/blob/master/controller/pagecontroller.php) need to be changed.

While I'm changing this I would additionally unify the JSON responses to the following form:
**Successful request:**
```javascript
{
  "status": "success",
  "data": {
    /* Application-specific data would go here. */
  },
  "message": null /* Or optional success message */
}
```
**Failed request:**
```javascript
{
  "status": "error",
  "data": null, /* or optional error payload */
  "message": "Error xyz has occurred"
}
```
source: http://stackoverflow.com/a/12979961

**Comment by Henni** [comment]
taskscontroller.php split up is in work: #195

**Comment by raimund-schluessler** [comment]
@Henni Done with #203?

**Comment by Henni** [comment]
Almost...
I still want to work on the json responses.
Please have a look at #205
