### ISSUE TITLE
Call to undefined method Sabre\\VObject\\Component\\VTodo::getAsString

### ISSUE THREAD

**Issue by blaskovic** [owncloud/tasks#211]
After upgrading owncloud to 8.0.5, tasks stopped working. I can see the same issue as someone here:
https://forum.owncloud.org/viewtopic.php?t=28901&p=89995

Even with the same error:
[Fri Jul 03 21:57:16.382908 2015] [fcgid:warn] [pid 21338] [client 89.102.11.84:38242] mod_fcgid: stderr: PHP Fatal error:  Call to undefined method Sabre\\VObject\\Component\\VTodo::getAsString() in /var/www/path/to/web/apps/calendar/lib/object.php on line 556, referer: https://domain.tld/index.php/apps/tasks/

**Comment by Henni** [comment]
@blaskovic are you using the current master of the app?
The current master and soon 0.7 release require owncloud 8.1.
Please use the last stable release (0.6) instead.

**Comment by blaskovic** [comment]
$ git checkout v0.6
HEAD is now at 75d758a... Increment version, add info

Aaaand its working. Thank you!
