### ISSUE TITLE
fix date entry via keyboard

### ISSUE THREAD

**Issue by EtlamGit** [owncloud/tasks#213]
I'm not able to type the start/end date via the keyboard.
All numbers are handled correctly, but no separator is possible ( . - ).
Therefore the date can not be parsed.

"/" as separator is possible, but can not be parsed.

The green check mark also does not work for me. Only RETURN updates the date information.

In case this is working for you, I'm using German keyboard layout. And in Germany date format would by dd.mm.yyyy or from ISO 8601: yyyy-mm-dd

**Comment by sahne123** [comment]
see #29

**Comment by raimund-schluessler** [comment]
Closing in favor of #29.

**Comment by Henni** [comment]
Thanks @sahne123 for referencing.
@EtlamGit please add to #29 if you have additional information.

I'll close this as duplicate
