### ISSUE TITLE
Release to appstore

### ISSUE THREAD

**Issue by raimund-schluessler** [owncloud/tasks#214]
@Henni I updated my productive server to oC8.1 and installed tasks v0.7. Besides a small problem with a broken reminder which I fixed, no problems seem to occur. I would suggest, we test the app a bit and if no other problems are found, we release v0.7 to the appstore on Thursday.

**Comment by pvanek** [comment]
I cannot load tasks into 8.1 from appstore right now. Ending in:

```
vps:/srv/www/htdocs/owncloud # sudo -u wwwrun php ./occ upgrade
ownCloud or one of the apps require upgrade - only a limited number of commands are available
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Updating <tasks> ...
PHP Fatal error:  Class 'OC_VObject' not found in /srv/www/htdocs/owncloud/apps/tasks/appinfo/update.php on line 27
```

then it stays in infinite "upgrade" loop, meaning that when I switch off maintenance flag in config file it goes to upgrade again

**Comment by raimund-schluessler** [comment]
Please see https://github.com/owncloud/tasks/issues/216. You use an old version of Tasks not compatible with oC8.1

**Comment by Henni** [comment]
@raimund-schluessler I think we can publish the app now.

**Comment by raimund-schluessler** [comment]
I am currently on it :)

**Comment by raimund-schluessler** [comment]
I had to release an updated version 0.7.1 where I fixed the update script. However, automatically installing the app from the appstore now works, so I think everything should be fine now.

**Comment by pvanek** [comment]
confirmed - all works now. Thanks.
