### ISSUE TITLE
Settings menu does not show

### ISSUE THREAD

**Issue by raimund-schluessler** [owncloud/tasks#215]
@Henni The settings menu does not show on oC8.1 with tasks v0.7-beta.2.
The error message is
``` javascript
TypeError: event.target.closest is not a function
	if (button === event.target.closest('[data-apps-slide-toggle]')) {
```
at https://github.com/owncloud/core/blob/9a0b0ba4889142d1b105bcf7df2b5b79864b8013/core/js/apps.js#L61

**Comment by Henni** [comment]
It works for me!
Please try if this fixes your problem:
```javascript
if (button === $(event.target).closest('[data-apps-slide-toggle]')) {
```

**Comment by Henni** [comment]
@raimund-schluessler which browser do you use?

**Comment by raimund-schluessler** [comment]
@Henni It does work on my development server which I only access by the latest Firefox or Chrome version (Windows).

It does not work on my productive server which I currently access by Firefox ESR 31.1.1. I can't tell how it behaves on this server with a later Firefox version at the moment, since I am at work. I will test it this evening, but I guess your patch will fix it.

**Comment by Henni** [comment]
I think I understand the problem. One second...

**Comment by raimund-schluessler** [comment]
Thanks, I didn't knew, that this is a built-in method in modern browsers. But it explains the problem :wink:

**Comment by raimund-schluessler** [comment]
Closing the issue, as it is not a Tasks problem.
