### ISSUE TITLE
Tasks are not shown since update to OC 8.1

### ISSUE THREAD

**Issue by wikon** [owncloud/tasks#216]
After updating to OC 8.1 and updating the tasks app, all the tasks are gone.

In the logs there is an error message:

{"reqId":"v\/VR5hBpty\/gWff\/3XLv","remoteAddr":"172.29.x.x","app":"PHP","message":"Class 'OC_VObject' not found at \/var\/www\/owncloud\/apps\/tasks\/controller\/helper.php#31","level":3,"time":"2015-07-08T11:09:29+00:00"}

**Comment by raimund-schluessler** [comment]
You don't use the current version of the tasks app as line 31 of ```helper.php``` is different to your error message: https://github.com/owncloud/tasks/blob/master/controller/helper.php#L31
The version you use is not compatible with oC8.1, so please update to the correct version.

Please use v0.7: https://github.com/owncloud/tasks/releases/tag/v0.7-beta.2

**Comment by wikon** [comment]
v0.7beta pre-release? Naja, wenigstens funktioniert's ;-).
Danke

**Comment by raimund-schluessler** [comment]
The final release is scheduled for tomorrow. In case we don't find any bugs, it will be identical to the beta.2. On my (productive) server beta.2 is working without problems at the moment.
