### ISSUE TITLE
Gantt view of tasks?

### ISSUE THREAD

**Issue by poVoq** [owncloud/tasks#219]
https://github.com/robicch/jQueryGantt

might work as a way to show tasks and easily edit their timing. Thanks!

**Comment by Henni** [comment]
Interesting idea!
Looks like a useful functionality. But probably won't be implemented soon because we have other issues to fix.

@raimund-schluessler what do you think?

**Comment by raimund-schluessler** [comment]
Hm, I would like to keep the app simple. And this doesn't look simple. I don't know if this is even interesting for many users. Lets keep the issue open, but it won't get implemented fast as there are by far more usefull features in my opinion.

**Comment by malsony** [comment]
One more vote for this function. Actually, Gantt Chart is more intuitive.

**Comment by hitam4450** [comment]
well, how about fork Task to develop a separate  app for the classical **project management** approach ?

regards, hitam4450

**Comment by hitam4450** [comment]
I certainly support the idea of implementing a gnatt view!
