### ISSUE TITLE
Unable to enable upgrade when calendar is not installed

### ISSUE THREAD

**Issue by binarykitchen** [owncloud/tasks#220]
I do not have the calendar app installed but have the tasks app installed and failed doing the `upgrade` command on owncloud v8.1 + Ubuntu 15.4

```
$ sudo -u www-data php occ upgrade -vvv
ownCloud or one of the apps require upgrade - only a limited number of commands are available
Checked database schema update
Checked database schema update for apps
Updated database
Updating <tasks> ...
PHP Fatal error:  Class 'OC_Calendar_Object' not found in /var/www/owncloud/apps/tasks/appinfo/update.php on line 21
```

If the calendar app is really a requirement for the tasks app then a warning should have appeared when I installed it without the calendar.

**Comment by raimund-schluessler** [comment]
The version you are using is not compatible with oC8.1. You have to use v0.7 or higher of the tasks app.

However, the calendar app is required to run tasks since calendar provides the CalDAV backend. I will check if we can prevent installing tasks when calendar is not enabled.

**Comment by raimund-schluessler** [comment]
Closing in favor of #221.
