### ISSUE TITLE
Prevent enabling tasks if calendar app is not installed

### ISSUE THREAD

**Issue by raimund-schluessler** [owncloud/tasks#221]
It would be good if we could prevent enabling the tasks app if the calendar app is not installed. I know inter-app dependencies are not wanted and run contrary to the owncloud design paradigma, but Tasks requires the CalDAV backend which is provided by calendar. So this dependency might not be resolved until e.g. https://github.com/owncloud/core/issues/5939 is implemented.

However, https://github.com/owncloud/core/issues/10777 didn't implement a dependency check for apps, for the reasons given above.

@DeepDiver1975 Can we still prevent installing Tasks somehow, or at least warn the user about the problems?

**Comment by binarykitchen** [comment]
That's a good ticket and I very welcome such a dependency check

**Comment by raimund-schluessler** [comment]
We won't be able to prevent enabling the app as https://github.com/owncloud/core/issues/18710 was neglected. However, we will try to add a notification when enabling tasks without calendar in https://github.com/owncloud/tasks/issues/249
