### ISSUE TITLE
Add .editorconfig

### ISSUE THREAD

**Issue by xf-** [owncloud/tasks#223]
Add a .editorconfig to improve the code.

A lot of editors support editorconfig or a plugin is available.
http://editorconfig.org/#download

For example the style.less has tabs and spaces mixed and the editor uses the default setting.

Current case:
I'm saving a file lines with spaces at the end will be trimed and included in diff.

**Comment by raimund-schluessler** [comment]
I just converted the spaces to tabs in style.less.

However, this might be helpful. @Henni What do you think? Should not hurt to add such a file.

**Comment by Henni** [comment]
Never heard of it but let's try it.
