### ISSUE TITLE
Align Settings

### ISSUE THREAD

**Issue by stefan-niedermann** [owncloud/tasks#227]
Current
![settings](https://cloud.githubusercontent.com/assets/4741199/8800807/10b65d82-2fb6-11e5-963c-59a14ee95a5d.png)

Expected
![settings-ordered](https://cloud.githubusercontent.com/assets/4741199/8800808/163dae04-2fb6-11e5-8f51-d446dd709218.png)

**Comment by raimund-schluessler** [comment]
Duplication of #222, already fixed in master with https://github.com/owncloud/tasks/commit/30774f7050a5df76e58a35787ab9d8ca1974b947.

**Comment by stefan-niedermann** [comment]
sorry, my fault... didn't see...

**Comment by raimund-schluessler** [comment]
No problem ;)
