### ISSUE TITLE
Add keyboard shortcuts

### ISSUE THREAD

**Issue by mpeterson** [owncloud/tasks#23]
To go through the items and modify them.

**Comment by alfish2000** [comment]
And to open the Search e.g. with "Strg-F"

**Comment by raimund-schluessler** [comment]
I am not sure about the "Strg-F" proposal, as this is a shortcut for opening the internal search in most browsers. Also with https://github.com/owncloud/tasks/issues/120 the search input field will vanish.

**Comment by alfish2000** [comment]
Yes.
Strg-F is the browser search too.
I thought the same but I had no better idea for a "Search Shortcut" :-)
Please see my comment at #122 about keeping the internal search additionally.

**Comment by ccoenen** [comment]
There's a working example of keyboard shortcuts in the [news app](https://github.com/owncloud/news). I think they did this quite well.
