### ISSUE TITLE
Hide task only calendars from calendar

### ISSUE THREAD

**Issue by ponychicken** [owncloud/tasks#230]
I have a number of task lists that have no connection to any kind of calendar. Still they appear in my calendar view on the website as well as on any device syncing the calendar via CalDav. It might be preferable to hide any calendar that doesn't have an event, but only tasks.

**Comment by plinss** [comment]
+1 
I was previously using DAViCal and task lists created via iOS or OSX reminders apps did not appear in calendar apps synced via CalDAV.

It would also be useful to not list event only calendars as task lists.

As a related note, turning off a calendar in the ownCloud Calendar app also hides the calendar in the ownCloud Tasks app, so there's no way to decouple task lists and calendars.

**Comment by raimund-schluessler** [comment]
This is an issue which has to be solved in the Calendar app. Please report it in https://github.com/owncloud/calendar.

For the feature to hide task lists in the Tasks app please see https://github.com/owncloud/tasks/issues/138

**Comment by plinss** [comment]
Note that the issue (in my case) isn't the task calendars showing up in the ownCloud Calendar app, it's them showing up in third party Calendar apps, like iOS. Is that an issue to be solved in the Calendar app or the core calendaring?

**Comment by raimund-schluessler** [comment]
@plinss They do show up in iOS because when they are created it is set that they may also contain events. We choose this solution, because the CalDAV specification forbids to change this later on (because what would happen with a calendar that contains tasks and you set the calendar to "events only"?).

In iOS (and I think Android too) you can deselect the calendar from showing up, so I don't see this as a problem.

**Comment by plinss** [comment]
I can turn off the extra calendars in the iOS calendar app, but I can't turn off the calendars in the iOS Reminders app. It would be nice to select the calendar type on creation if it can't be changed later (which is understandable)
