### ISSUE TITLE
Shared tasks don't appear on Android

### ISSUE THREAD

**Issue by jluttine** [owncloud/tasks#231]
If I share a calendar (tasks) to another user, he/she can see the tasks on the web interface but Android client doesn't show them. It finds the tasks list but shows zero tasks for it. I've tried manually refreshing and syncing several times on all clients etc. I believe this is not a duplicate of #47 and #6, but I'm not sure.

**Comment by raimund-schluessler** [comment]
This seems to be a CalDAV issue. The CalDAV backend is provided by the calendar app. Please check if you can share calendar events and report an issue in the calendar repository under https://github.com/owncloud/calendar.

**Comment by raimund-schluessler** [comment]
CalDAV backend is now in core. Please report this again there if the issue still persists.
