### ISSUE TITLE
Editing tasks leads to duplicate tasks

### ISSUE THREAD

**Issue by jluttine** [owncloud/tasks#232]
If I edit a task, after a sync (I think so) I will have a duplicate of the task: the old version and the new version. I need to manually delete the old version(s).

**Comment by raimund-schluessler** [comment]
How do you edit the task? Via CalDAV or in the webinterface? If you edit it via CalDAV, then it is a CalDAV issue. Please report in the calendar repository https://github.com/owncloud/calendar.

**Comment by jluttine** [comment]
I use Android client to edit. Syncing is done with DAVdroid. Ok, I'll report the issue there.
