### ISSUE TITLE
Support multiple parents for the same task

### ISSUE THREAD

**Issue by raimund-schluessler** [owncloud/tasks#235]
@AshleyYakeley wrote:

> There are different levels of subtask support...
> 
>    Level 0: All tasks are top level, there are no subtasks.
>    Level 1: Top-level tasks may have subtasks. Subtasks may not have subtasks.
>    Level 2: "Tree": every task has zero or one parent task, up to arbitrary depth. (Tasks without parent tasks are top-level tasks.)
>    Level 3: "DAG": every task has zero or more parent tasks. (Cycles of parents are forbidden.) This allows diamond dependencies of tasks, for example, task A depends on tasks B & C, which both depend on task D. Task D is shown as "do-able", once it's done, then tasks B & C become "do-able".
> 
> I'm currently using "Getting Things Gnome", which is at level 3, the only task app I know at this level. It's great for people like me who like to break things down into tiny pieces.

**Comment by raimund-schluessler** [comment]
Following your classification, this app here is at level 2. Tasks only have one parent, but can have multiple subtasks which themselves may have subtasks.

As far as I understand the iCalendar specification, which the used CalDAV implementation relies on, having multiple parents is not supported (see http://tools.ietf.org/html/rfc5545#section-3.8.4.5). This means implementing level 3 is not possible without breaking the specification (which we don't want ;).

**Comment by raimund-schluessler** [comment]
We could define multiple RELATED-TO properties (as they could also be childs or siblings), but I don't know if it is legitimate to define multiple parents.

Besides from that I am not sure if we really want this, as it is maybe to difficult to understand this concept. Also, could you elaborate on how the GUI for this feature looks like (e.g. how can I define multiple parents, how can I remove the parent relationship, etc.). Thanks!

**Comment by AshleyYakeley** [comment]
As far as I can tell, multiple parents does not break RFC 5545. And even if owncloud/tasks does not support it, CalDAV clients might. How should owncloud/tasks handle a CalDAV POST containing iCalendar objects with multiple parents?

But you are right to point out that figuring out a sensible UI design is not obvious. Here's what Getting Things Gnome (a desktop app) does...

For a "diamond dependency", task D simply appears twice in its tree view, like this:

* A
  * B
    * D
  * C
    * D

Creating this is slightly awkward, as you have to go to task B and copy its link to D onto task C. However, it will correctly prevent circular dependency. Ideally it would have a way of picking an existing task to add as a dependency.

**Comment by jh72de** [comment]
There's nothing in the spec that forbids this. So clients will probably do it anyway, because it's reflecting real life.
