### ISSUE TITLE
Give visual feedback for the calendar dependency

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/tasks#249]
Took me quite some time to figure out, why the tasks app was not showing up.
The problem was I didn't have the calendar installed.

I think it is too complicated to get tasks working without calendar (just have some missing features?)?
If so, there should be visual feedback to why the app is not working, e.g.
add a little JS file that runs:
```js
			OC.Notification.showTemporary(t('tasks', 'Tasks app is unavailable because the calendar is not installed'));
```
That will show the following message for 7 seconds:
![bildschirmfoto vom 2015-08-31 16 23 55](https://cloud.githubusercontent.com/assets/213943/9580949/ca7ec658-4ffc-11e5-9db3-4f9a48bf7aa1.png)

**Comment by nickvergessen** [comment]
Well #250 already helps making it visual

**Comment by raimund-schluessler** [comment]
Indeed, and maybe we can have https://github.com/owncloud/core/pull/18714

**Comment by karlitschek** [comment]
a warning like that might make sense. the real clean solution would be to avoid a dependency at all.
