### ISSUE TITLE
Tasks app logs out current user in firefox

### ISSUE THREAD

**Issue by Henni** [owncloud/tasks#253]
Somehow opening `example.com/owncloud/index.php/apps/tasks` logs out the current user.
This happens in firefox but doesn't in chrome.

**Comment by raimund-schluessler** [comment]
Hm, I can't reproduce this. opening ```owncloudroot/index.php/apps/tasks``` correctly forwards me to ```owncloudroot/index.php/apps/tasks#/lists/all``` both on Firefox and Chrome.

**Comment by Henni** [comment]
After a restart I can't reproduce it anymore.
I'll close this issue until it happens again.

**Comment by raimund-schluessler** [comment]
Weird.
