### ISSUE TITLE
Version 0.8 - Subtask

### ISSUE THREAD

**Issue by hitam4450** [owncloud/tasks#264]
How to open / create subtask in Version 0.8 ?

regards, hitam4450

**Comment by raimund-schluessler** [comment]
The direct way is to click on the plus sign on the right side of a task, but you can as well just drag and drop a task onto another one and make it a subtask that way.

**Comment by hitam4450** [comment]
I do not see a + sign, however hovering about the location it will show the option to add a subtask (sorry, can't be seen on the screen shot)

![task](https://cloud.githubusercontent.com/assets/9738727/9798441/2b43d51c-5801-11e5-8c7b-b414b4a25afa.png)

**Comment by raimund-schluessler** [comment]
It is possible that you have to reload the page twice in order to flush the cached svg image (at least this always happens for me).

**Comment by hitam4450** [comment]
Hi, Ok it worked for me as well! After reloading the Browser(ff40) tab once, I could see the + sign!
Thanks for your fast reply!
regards, hitam4450
