### ISSUE TITLE
Task input field has awkward outline on focus.

### ISSUE THREAD

**Issue by gillisig** [owncloud/tasks#268]
There is an awkward outline that appears on the input field when adding a new task, when using Chrome, like seen in the screenshot below: 

![screen shot 2015-09-17 at 15 58 21](https://cloud.githubusercontent.com/assets/5390864/9938688/13c671b0-5d56-11e5-9fea-319f761da0c9.png)

It looks like a different kind of focus is being applied by changing the background from gray to white so this outline is not needed. It can be fixed by applying `outline: none;` to the input.

**Comment by raimund-schluessler** [comment]
I don't know if this was still an issue, but I just added ```outline: none;``` to the input field, so it should be could anyway now.
