### ISSUE TITLE
Button "Load finished tasks" has no function

### ISSUE THREAD

**Issue by DemoFreak** [owncloud/tasks#269]
V 0.8.0
OC 8.1.3

Pressing "Load remaining finished tasks" (translation by me, in german it reads as "Die restlichen abgeschlossenen Aufgaben laden") in shared calendars don't load the finished tasks, but creates an additional calendar entry with empty name on the left. When this calendar/list is selected, the "All tasks" collection is displayed instead.

**Comment by Henni** [comment]
@DemoFreak thanks for the feedback. We are currently fixing some of the issues with shared calendars, but I'm not sure if this is one of them.
@raimund-schluessler @sahne123 do you know more about this?

**Comment by DemoFreak** [comment]
@Henni I didn't check so far if this behavior is limited to shared lists. I simply have no tasks in "Default calendar". ;-)
But I could check this if it would help. If I could do some other tests please let me know.

**Comment by Henni** [comment]
@DemoFreak would be great if you could test this for normal lists as well!

**Comment by DemoFreak** [comment]
Done.

First of all I had to reload the whole Tasks app, as before this the display limitation didn't take place. All finished tasks were displayed until app reload.

After reload the "load remaining finished tasks" button appeared and it works like intended.
All remaining tasks get displayed (and stay displayed until app reload, regardless if one switch between lists/collections).

**Comment by raimund-schluessler** [comment]
> First of all I had to reload the whole Tasks app, as before this the display limitation didn't take place. All finished tasks were displayed until app reload.
>
> After reload the "load remaining finished tasks" button appeared and it works like intended.
All remaining tasks get displayed (and stay displayed until app reload, regardless if one switch between lists/collections).

This is the intended behavior. This function only limits the number of displayed tasks while (re)loading the app, in order to save bandwidth and make the app work faster. Completed tasks will not be hidden from the app directly after they were completed, as this would not speed up the app.

> Pressing "Load remaining finished tasks" (translation by me, in german it reads as "Die restlichen abgeschlossenen Aufgaben laden") in shared calendars don't load the finished tasks, but creates an additional calendar entry with empty name on the left. When this calendar/list is selected, the "All tasks" collection is displayed instead.

This is a (weird) bug.

**Comment by raimund-schluessler** [comment]
Works as expected in master with oc9 now. Please check again and report if not.
