### ISSUE TITLE
[Feature request] Import list[s] from CSV or on paste

### ISSUE THREAD

**Issue by agilob** [owncloud/tasks#271]
It should be possible to somehow import existing lists from common formats like .csv or flat file.

Two simple implementation I can think about are:
1. import from csv file where user can select which column has task name
2. detect Ctrl+V of multi-line text and add one line as one task

Both formats are easy to get by user by importing any format (csv or flat file) in Excel/LO-Calc, so it should be a problem for user to get the format.

CSV file format is used by other todo managers like out of milk, kmail, (out of date) thunderbird plugin or google task.

**Comment by kordianbruck** [comment]
Similar to issue #182
