### ISSUE TITLE
VTODO not work properly when UID is missing

### ISSUE THREAD

**Issue by onewaypub** [owncloud/tasks#272]
### Steps to reproduce
1. Send VTODO to owncloud with activated task app without a UID. For example with Comodo OutlookDAV/v5.2

### Expected behaviour
Not error massage occur

A workaround would be nice

### Actual behaviour
since a few versions I got many of the following errors:

"Every VTODO component must have an UID"

It seems this is a bug, because the UID property is marked as optional:

A "VTODO" calendar component is defined by the
following notation:

see https://www.ietf.org/rfc/rfc2445.txt ( 4.6.2 To-do Component )

  todoc      = "BEGIN" ":" "VTODO" CRLF
               todoprop *alarmc
               "END" ":" "VTODO" CRLF

  todoprop   = *(

             ; the following are optional,
             ; but MUST NOT occur more than once

             class / completed / created / description / dtstamp /
             dtstart / geo / last-mod / location / organizer /
             percent / priority / recurid / seq / status /
             summary / uid / url /

             ; either 'due' or 'duration' may appear in
             ; a 'todoprop', but 'due' and 'duration'
             ; MUST NOT occur in the same 'todoprop'

             due / duration /

             ; the following are optional,
             ; and MAY occur more than once
             attach / attendee / categories / comment / contact /
             exdate / exrule / rstatus / related / resources /
             rdate / rrule / x-prop

             )

### Server configuration
**Operating system**:
Ubuntu 15.04
**Web server:**
 Apache/2.4.12 (Ubuntu)
**Database:**
10.0.20-MariaDB-0ubuntu0.15.04.1
**PHP version:**
PHP 5.6.4-4ubuntu6.3
**ownCloud version:** (see ownCloud admin page)
8.1.3

**List of activated apps:**

* Activity 2.0.2
* Default encryption module 1.0.0
* Deleted files 0.6.3
* Documents 0.10.2
* External Sites 1.2
* External storage support 0.2.3
* File Locking
* First Run Wizard 1.1
* PDF Viewer 0.7
* Pictures 0.6.0
* Share Files 0.6.2
* Text Editor 0.4
* Updater 0.6
* Versions 1.0.6
* Video Viewer 0.1.3
* Calendar 0.7.3
* Contacts 0.4.0.0
* News 6.0.5
* Tasks 0.8
* Notes 0.8

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => '51effefe75573',
  'passwordsalt' => '',
  'datadirectory' => '...',
  'dbtype' => 'mysql',
  'version' => '8.1.3.0',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'mail.gmx.com',
  'mail_smtpsecure' => 'tls',
  'mail_smtpauth' => 1,
  'mail_smtpname' => '',
  'mail_smtppassword' => '',
  'mail_domain' => 'gmx.de',
  'forcessl' => true,
  'logtimezone' => 'Europe/Berlin',
  'log_type' => 'owncloud',
  'log_authfailip' => true,
  'theme' => '',
  'maintenance' => false,
  'maxZipInputSize' => 0,
  'overwritewebroot' => '/owncloud',
  'allowZipDownload' => true,
  'overwrite.cli.url' => '/owncloud',
  'trusted_domains' =>
  array (
...
  ),
  'mail_from_address' => '',
  'mail_smtpport' => '587',
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'secret' => '',
  'loglevel' => 3,
  'asset-pipeline.enabled' => true,
  'forceSSLforSubdomains' => true,
  'log_rotate_size' => 10485760,
  'mail_smtpauthtype' => 'LOGIN',
  'filelocking.enabled' => 'true',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
  ),
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Outlook with Comodo OutlookDAV v5.2 Plugin

**Operating system:**
Windows ?

#### Web server error log
not important here

#### ownCloud log (data/owncloud.log)
Exception: {"Message":"HTTP\/1.1 400 Every VTODO component must have an UID","Code":0,"Trace":"#0 \/var\/www\/public\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Plugin.php(832): Sabre\\CalDAV\\Plugin->validateICalendar('BEGIN:VCALENDAR...', 'calendars\/jgajd...', false, Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response), true)\n#1 [internal function]: Sabre\\CalDAV\\Plugin->beforeCreateFile('calendars\/jgajd...', 'BEGIN:VCALENDAR...', Object(OC_Connector_Sabre_CalDAV_Calendar), false)\n#2 \/var\/www\/public\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#3 \/var\/www\/public\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1051): Sabre\\Event\\EventEmitter->emit('beforeCreateFil...', Array)\n#4 \/var\/www\/public\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(513): Sabre\\DAV\\Server->createFile('calendars\/jgajd...', Resource id #36, NULL)\n#5 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#6 \/var\/www\/public\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#7 \/var\/www\/public\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#8 \/var\/www\/public\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#9 \/var\/www\/public\/owncloud\/apps\/calendar\/appinfo\/remote.php(57): Sabre\\DAV\\Server->exec()\n#10 \/var\/www\/public\/owncloud\/remote.php(132): require_once('\/var\/www\/public...')\n#11 {main}","File":"\/var\/www\/public\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Plugin.php","Line":915}

#### Browser log
not important here

**Comment by raimund-schluessler** [comment]
Please try OC 9 which is now in charge of handling all the CalDAV related stuff.
