### ISSUE TITLE
Not compatible with ownCloud 8.2

### ISSUE THREAD

**Issue by strugee** [owncloud/tasks#275]
In the [ownCloud Apps market][1], Tasks is marked as incompatible with ownCloud 8.2. Whether or not it's actually incompatible or just requires a version bump, I don't know. Either way, this is blocking my upgrade.

 [1]: https://apps.owncloud.com/content/show.php/Tasks?content=164356

**Comment by seraphyn** [comment]
Works from my side absolut flawlessy
And if you would like to upgrade you owncloud, you've to disable all 3rd Party apps as mentioned in the documentation of owncloud.
After this you have to upgrade, via webui or occ and install and enable all 3rd party apps.

See here [here](https://doc.owncloud.org/server/8.1/admin_manual/maintenance/upgrade.html) : 
> Before upgrading to a new major release, always first review any third-party apps you have installed  for compatibility with the new ownCloud release. Any apps that are not developed by ownCloud show a 3rd party designation. Install unsupported apps at your own risk. Then, before the upgrade, they must all be disabled. After the upgrade is complete and you are sure they are compatible with the new ownCloud release you may re-enable them.

**Comment by strugee** [comment]
@seraphyn I'm aware of how to upgrade my ownCloud, and I've read the docs you're referring to.

You'll note that in the paragraph you just quoted, it says:

> Before upgrading to a new major release, always first review any third-party apps you have installed for compatibility with the new ownCloud release.

I did this by looking at the ownCloud apps market, which indicated that Tasks wasn't compatible with 8.2. Hence why I'm holding off on upgrading, and hence this issue.

**Comment by Henni** [comment]
@raimund-schluessler can we release a new release soon? Maybe just 0.8.1 to update the max-version?

**Comment by raimund-schluessler** [comment]
In principle yes, but I crashed my development environment yesterday, so it might take a little longer.

**Comment by strugee** [comment]
@raimund-schluessler any chance you'd be able to do this now that a couple weeks have gone by?

**Comment by raimund-schluessler** [comment]
I intend to do so the next days, I just set up my development environment again. Sorry for the delay.

**Comment by raimund-schluessler** [comment]
@strugee Should be good now, and oC8.2.1 is also available :rocket: .

**Comment by strugee** [comment]
@raimund-schluessler awesome!

**Comment by RealRancor** [comment]
@raimund-schluessler Any chances that there are some issues with publishing 0.8.1 at the appstore? This version seems to not show up for oC 8.2.1 within the oC internal appstore but others like documents, mail and news are showing up just fine.

**Comment by raimund-schluessler** [comment]
@RealRancor Hm, I don't know, I pusblished it as always. I will have to take a look.

**Comment by silverhook** [comment]
I can confirm what @RealRancor described – on oC 8.2.1 I cannot find Tasks in app store, whether the experimental apps are enabled or not.

**Comment by stephengraf** [comment]
@raimund-schluessler Have you had a chance to look into this? As @silverhook  confirmed, the task app is still not available in the  productivity apps menu.  A such this issue should be reopened.

**Comment by Tronde** [comment]
I can confirm that the app is not available in the productivity apps menu of ownCloud 8.2.1.

After the upgrade from 8.1.4 to 8.2.1 i missed it and couldn't enalbe it again. As a workaround I copyied the apps folder which is within the apps subdirectory from my backup back to the apps subdirectory of my current ownclod installation. Then I was able to activate the app again.

Regards,
Tronde

**Comment by zhuravlev-alexey** [comment]
Have the same problem. After update to 8.2.1 can't find it in apps menu.

**Comment by CriticalNoob** [comment]
Not available from a fresh 8.2.2 install.
I guess the development stopped... Sad.

**Comment by RealRancor** [comment]
@CriticalNoob Sorry, but thats just b******t. Just read this complete issue and you will see that there is just an issue with correctly publishing the app.

**Comment by CriticalNoob** [comment]
The app is not publicly available and no news for a month, not a sign of active development I'm sorry I exaggerating when I say dead. I should have say stalled. But I understand that as an open source freeware, dev have jobs and other things to do.

**Comment by RealRancor** [comment]
Thats also not true. The app is publicly available at:

https://apps.owncloud.com/content/show.php/Tasks?content=164356
https://github.com/owncloud/tasks/releases

Its currently just not installable via the appstore...

**Comment by silverhook** [comment]
@CriticalNoob, I’m just as anxiously waiting for Tasks to pop up in the app store as you are (especially since I’m having some trouble with ownCloud calendars syncing in KDE 4). But I’m sure @raimund-schluessler or someone else will look into this as soon as they can. In addition to this being (likely) work someone is doing in their free time, it is holiday season, so people deserve some time off.

:gift: :christmas_tree: :wine_glass:

**Comment by raimund-schluessler** [comment]
I am sorry guys, that this issue still exists. I don't really have a clue why it is not showing up in the appstore, since I published it as usual. As a workaround you have to manually download and install it (either from the appstore, or from github here), it works just fine with oC 8.2.1.

As I only work on this app in my freetime and currently write my PHD thesis I don't have time to look into this at the moment. Sorry for the inconvenience.

**Comment by silverhook** [comment]
> As I only work on this app in my freetime and currently write my PHD thesis I don't have time to look into this at the moment. Sorry for the inconvenience.

That’s totally understandable :smiley_cat: I guess you’re open to a pull request or other help, should anyone find a solution on their own?

BTW, all the best for your PhD! I’m right now taking a 2min break from writing my LL.M. thesis to reply you :smirk_cat:

**Comment by RealRancor** [comment]
Mhhh, seems the same is also happening for the Notes app: https://github.com/owncloud/notes/issues/185

Not quite sure why both apps are affected. Is there some one we can pull in here to give support?

**Comment by silverhook** [comment]
@raimund-schluessler Can you try the solution @RealRancor suggested?

It seems like it could solve the issue and it’s more or less just fixing a typo.

**Comment by RealRancor** [comment]
@LukasReschke Sorry to ping you also here. From what i can see it should be all fine here. The app is not "approved" but it should at least show up when experimental apps are enabled or am i wrong?

**Comment by LukasReschke** [comment]
@RealRancor There is a bug in the appstore it seems. I added a workaround, see https://github.com/owncloud/appstore-issues/issues/39 for details :speak_no_evil:

**Comment by raimund-schluessler** [comment]
So, setting compatibility to 9.1 will work around this? If yes, I will change the setting in the appstore in case you don't need the wrong behaviour for fixing the issue.

**Comment by RealRancor** [comment]
@LukasReschke Thanks for having a look at this. Just tested and the installation now works fine.

**Comment by raimund-schluessler** [comment]
@LukasReschke Did you change anything at the appstore? Or why does it work now?

**Comment by silverhook** [comment]
Shows up and installs now :)
