### ISSUE TITLE
Filter tasks by category

### ISSUE THREAD

**Issue by avanc** [owncloud/tasks#276]
The tasks app now supports categories which is great to.. well... categorize tasks.
However, it should be possible to filter tasks by its categories.
E.g. show all tasks with category "Grocery".

**Comment by raimund-schluessler** [comment]
As a quick solution you can use the global search box on the top right corner to search for tasks containing the search term. The categories are searched too, so you will find all tasks with a given category (plus all tasks containing the search term as title, note etc.)

**Comment by Bugsbane** [comment]
Just a quick note that from a ui perspective I was expecting that when I clicked on one of the categories listed in a to-do item, that it would take me to a list of items marked with that same category, not just into the individual todo item.

**Comment by olantrust** [comment]
Integration with the global Tag system see: #292 would perhaps be a better investment?
Would it produce the same results (using the built-in tag view?)

**Comment by strank** [comment]
+1 on the filtering tasks by category, as well as a way to list all known categories somewhere. Doesn't seem to be possible right now.

The workaround of searching for the tag/category does not work for me BTW.
