### ISSUE TITLE
"Collection visibility" in Parameters is mis-aligned when using French localization

### ISSUE THREAD

**Issue by Pastafarianist** [owncloud/tasks#277]
![image](https://cloud.githubusercontent.com/assets/1315874/11014671/d3b2870c-8551-11e5-9e6d-9edc939d1e5f.png)

ownCloud 8.1.4, Tasks 0.8, Chrome 46.0.2490.80 (64-bit), screen resolution 1366x768.

**Comment by raimund-schluessler** [comment]
Hm, we need to set maximum widths for the label and the dropdown then...
