### ISSUE TITLE
Switch to unified CalDAV endpoint

### ISSUE THREAD

**Issue by raimund-schluessler** [owncloud/tasks#280]
Migrate to the unified CalDAV endpoint in core to get rid of the dependency to the calendar app.
See https://github.com/owncloud/core/pull/20371

**Comment by Henni** [comment]
I found mainly two libraries for CalDAV:
https://github.com/gaye/dav
I currently use this for the [contacts app](https://github.com/Henni/contactsrework). It has a simple API but is missing some features like adding addressbooks or calendars (@irgendwie is currently adding this feature).
https://github.com/evert/davclient.js
This library will be used in core for the files app (see owncloud/core#16902).
The API isn't as advanced as the previous library. Therefore it is simpler to extend it but more difficult to use at the moment.

@raimund-schluessler have you managed to setup IRC? I'd like to talk about this in more detail on #owncloud-dev or #owncloud-tasks

**Comment by DeepDiver1975** [comment]
CalDAV just got merged into core!I'm happily looking forward to see tasks moving over!

**Comment by raimund-schluessler** [comment]
@Henni Is there a DAV library which can be used on the server side as we currently do? Or do we really want to change the approach completely?

PS: I currently have very limited time as I write my PHD thesis. So I can't promise I will have time to work on the tasks app a lot.

**Comment by Henni** [comment]
@raimund-schluessler I believe we can use sabre's vobject to access the new backend similarly to how we do it now.

**Comment by raimund-schluessler** [comment]
Is there a reason to not use the vobject? It seems to me that the calendar and contacts rework won't use it. Maybe we should all use the same architecture to keep it consistent.

**Comment by Henni** [comment]
The goal is to do all of it clientside and directly communicate with the CalDAV (or CardDAV) backend.
This way we only have to care about the client and owncloud core does the server side for us.
