### ISSUE TITLE
Black field on right side on android tablett inchrome browser

### ISSUE THREAD

**Issue by witzker** [owncloud/tasks#283]
Hi i open owncloud in chrome on android
When i click tasks in menu ok
When i click a task the window on right side opens BUT
2/3 of the window on the right is black.

How to solve?

**Comment by raimund-schluessler** [comment]
We need a bit more detail about which versions you use. Best would be to use the issue template https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

Also a screenshot would help.

Unfortunately I don't own an android tablet, so I can't reproduce this error. @Henni Do you have a tablet?

**Comment by Henni** [comment]
I own an android tablet, but we probably won't need it to figure this out.
@witzker could you also add a screenshot please.

**Comment by witzker** [comment]
![screenshot_2015-11-24-09-04-31](https://cloud.githubusercontent.com/assets/4120266/11361486/284d3b1a-928e-11e5-83f2-44e24f4c0776.png)
![screenshot_2015-11-24-09-05-18](https://cloud.githubusercontent.com/assets/4120266/11361487/28512018-928e-11e5-8451-b63c06215c74.png)
Hi i am new with owncloud can i give you admin login datas to see the configuration?

**Comment by witzker** [comment]
Any news?
Do you need login infos to see what's wrong?
Regards 
Witzker

**Comment by raimund-schluessler** [comment]
Is this still a problem? I can't check it myself, because I don't have an Android tablet. A PR would be welcome.

**Comment by raimund-schluessler** [comment]
Please reopen if it is still an issue.
