### ISSUE TITLE
Trying to upgrade Tasks on OC 8.2.1 leaves my site giving 503 error

### ISSUE THREAD

**Issue by Bugsbane** [owncloud/tasks#286]
Hi there,

I had Tasks installed on my ownCloud 8.2.1 install, and I noticed that there was an upgrade available. When I clicked "Upgrade" though and left it for a couple of hours, it was still telling me to wait when I got back.

When I refreshed the apps page, it still showed as having the upgrade available. Previously with other apps, I've often found that removing the app and then installing it again often helped so I went to try that here. When I tried to remove and reinstall the tasks app though, it once again stalled, asking me to wait forever. I attempted to run occ upgrade, which told me that ownCloud was already up to date. On going back to the site though, I now just get "502 Bad Gateway".

Nginx logs show this repeatedly:
````
[error] 15381#0: *20266 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: mydomain.com, request: "GET /index.php/apps/news/api/v1-2/cleanup/before-update HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "mydomain.com"
````

The last errors in the ownCloud log are:

````

{"reqId":"n27YRvgQfC7tH7xEphcy","remoteAddr":"58.179.254.124","app":"carddav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 System in maintenance mode.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: OC\\\\Connector\\\\Sabre\\\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/srv\\\/http\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/srv\\\/http\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/srv\\\/http\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/srv\\\/http\\\/webapps\\\/owncloud\\\/apps\\\/contacts\\\/appinfo\\\/remote.php(84): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/srv\\\/http\\\/webapps\\\/owncloud\\\/remote.php(137): require_once('\\\/srv\\\/http\\\/webap...')\\n#6 {main}\",\"File\":\"\\\/srv\\\/http\\\/webapps\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/maintenanceplugin.php\",\"Line\":84}","level":4,"time":"Sun , 20 Dec 2015 - 07 02 pm"}
{"reqId":"T27d\/olhAZEiyB1qm4cl","remoteAddr":"","app":"PHP","message":"file_get_contents(\/srv\/http\/webapps\/owncloud\/apps\/news\/appinfo\/checksum.json): failed to open stream: No such file or directory at \/srv\/http\/webapps\/owncloud\/apps\/news\/appinfo\/application.php#189","level":3,"time":"Sun , 20 Dec 2015 - 09 53 pm"}
{"reqId":"A1sqOxrWFs5jOFGG9aa6","remoteAddr":"","app":"PHP","message":"file_get_contents(\/srv\/http\/webapps\/owncloud\/apps\/news\/appinfo\/checksum.json): failed to open stream: No such file or directory at \/srv\/http\/webapps\/owncloud\/apps\/news\/appinfo\/application.php#189","level":3,"time":"Sun , 20 Dec 2015 - 09 54 pm"}
{"reqId":"3yZgPqfTiOcdA8irQefy","remoteAddr":"","app":"PHP","message":"file_get_contents(\/srv\/http\/webapps\/owncloud\/apps\/news\/appinfo\/checksum.json): failed to open stream: No such file or directory at \/srv\/http\/webapps\/owncloud\/apps\/news\/appinfo\/application.php#189","level":3,"time":"Sun , 20 Dec 2015 - 09 54 pm"}
{"reqId":"R7k5CFlnfseHW\/8wC3JE","remoteAddr":"","app":"PHP","message":"file_get_contents(\/srv\/http\/webapps\/owncloud\/apps\/news\/appinfo\/checksum.json): failed to open stream: No such file or directory at \/srv\/http\/webapps\/owncloud\/apps\/news\/appinfo\/application.php#189","level":3,"time":"Sun , 20 Dec 2015 - 09 54 pm"}
{"reqId":"F3sjdGtb2wHiK42cfzW7","remoteAddr":"","app":"PHP","message":"file_get_contents(\/srv\/http\/webapps\/owncloud\/apps\/news\/appinfo\/checksum.json): failed to open stream: No such file or directory at \/srv\/http\/webapps\/owncloud\/apps\/news\/appinfo\/application.php#189","level":3,"time":"Sun , 20 Dec 2015 - 09 55 pm"}
{"reqId":"5\/vP+VltTOb8c0mrOrTg","remoteAddr":"","app":"PHP","message":"file_get_contents(\/srv\/http\/webapps\/owncloud\/apps\/news\/appinfo\/checksum.json): failed to open stream: No such file or directory at \/srv\/http\/webapps\/owncloud\/apps\/news\/appinfo\/application.php#189","level":3,"time":"Sun , 20 Dec 2015 - 09 55 pm"}
{"reqId":"+aXmEkp9PhDOjFqxbyZM","remoteAddr":"127.0.0.1","app":"core","message":"can't remove app tasks. It is not installed.","level":3,"time":"Tue , 22 Dec 2015 - 01 10 am"}
{"reqId":"UDnv8f3j5\/sCpbjxx\/HO","remoteAddr":"127.0.0.1","app":"core","message":"can't remove app tasks. It is not installed.","level":3,"time":"Tue , 22 Dec 2015 - 01 14 am"}
{"reqId":"kFbDMFAo6sn1d7mtR+os","remoteAddr":"","app":"PHP","message":"file_get_contents(\/srv\/http\/webapps\/owncloud\/apps\/news\/appinfo\/checksum.json): failed to open stream: No such file or directory at \/srv\/http\/webapps\/owncloud\/apps\/news\/appinfo\/application.php#189","level":3,"time":"Tue , 22 Dec 2015 - 01 24 am"}

````

Disabling Tasks and News and using occ maintenance:repair doesn't seem to make any difference.

Despite these errors, the News app was working just fine before my attempted upgrade of Tasks took the site down, thus why I filed here.

**Comment by raimund-schluessler** [comment]
Upgrading Tasks should not lead to a broken news app. Is it possible that the news app was upgraded too (probably by accident). Try disabling both apps to get owncloud running again. Then enable Tasks too.

Sadly I can't give any support for the news app as I don't use or know it. If it keeps failing, please ask at the respective repository too.

**Comment by Bugsbane** [comment]
I did disable both apps via occ, but it didn't make any visible difference. I'll try posting over on the news repo, although I'm positive I didn't click on any upgrade there. Can using occ upgrade trigger apps to be upgraded? I thought that just upgraded core.

**Comment by Bugsbane** [comment]
Hmmm... this seems to be not entirely News related. I found the entire tasks folder was missing. When I downloaded it, renamed it to tasks, chowned it to my http user and put it in the apps folder, the 503 went away and I was told that the site was upgrading to 8.2.0 which it was aleady on. It said it was also going to upgrade a number of apps including Tasks, but with no mention of news.

After a success message, ownCloud gave a message to refresh the page, at which point I got a 503 again. News was disabled.

**Comment by raimund-schluessler** [comment]
I guess as https://github.com/owncloud/news/issues/901 is closed this issue here can be considered fixed too.

**Comment by Bugsbane** [comment]
Hard to say. I did a fresh install of ownCloud on a completely different machine, running a different operating system (Arch -> Debian) installing a different version of ownCloud (8.2.1 ->9.0.2) and I don't seem to be having the issue on the new version. I'm fine with it being closed though.
