### ISSUE TITLE
tasks and activity integration

### ISSUE THREAD

**Issue by nlienard** [owncloud/tasks#288]
Hi

With the new activity module in owncloud core; it would be great to integrate TASKS within.

For instance; there are 4 people working on the same tasks list, let say it is named "Project".
There are multiple items, named item1; subitem1, subitem2, item2; item3, itemN or whatever.

When 1 people update 1 task, there will be an event in Activity saying for instance:
-  "People1 updated Project list,  task item1 :new comment : xxxxx"
-  "People2 updated Project list; task item2, subitem3 : 30% completed"
-  "People2 updated Project list; task item1, subitem2 : Date due has changed from 2st of february to 23rd of February"
  Etc

Is that possible ?

It would help a lot for people using Owncloud as a project management tool and would facilitate move from ASANA to OWNCLOUD.

Thanks for your help;

Regards
Nico

**Comment by ccoenen** [comment]
#177 is also related to this.
