### ISSUE TITLE
Can't share tasks

### ISSUE THREAD

**Issue by Grunthos** [owncloud/tasks#289]
I've installed OC 8.2.2 and the latest Tasks app and Calendar app.

When I create a task with a start and due date of now-ish, it does not appear in my calendar.

Also, I see no way to share anything but whole calendars. I definitely can't see any option to share tasks or task lists.

**Comment by raimund-schluessler** [comment]
Tasks with start and due date do not appear in calendar by now. This has to be implemented in the Calendar app, see: https://github.com/owncloud/calendar/issues/499.

As for sharing tasks: see https://github.com/owncloud/tasks/issues/47.
