### ISSUE TITLE
Unify interpreting of dateformats, let user customize formats

### ISSUE THREAD

**Issue by raimund-schluessler** [owncloud/tasks#29]
The formatting of dates is mixed up when entering dates manually in the datepicker text box.

Furthermore, the user should be able to select which formatting he wants to use.

**Comment by ardichoke** [comment]
Additionally, the date box wants the date to be entered as dd.mm.yyyy, however it does not allow the use of '.' in the text input field (at least for me in Firefox). This means that typing a date in manually never works and results in the date being set to "Today" unless the calendar date picker is used.

**Comment by WolfgangEibner** [comment]
I can confirm this. It is impossible (in Firefox) to set a date by keybord input.
