### ISSUE TITLE
Tasks doesn't work with minified assets (asset-pipeline)

### ISSUE THREAD

**Issue by Couto** [owncloud/tasks#290]
### Steps to reproduce
1. Enable `'asset-pipeline.enabled' => true` in the `config/config.php`
2. In the browser, go to the owncloud instance website
3. Go to the Tasks app `/index.php/apps/tasks/`

### Expected behaviour
The Tasks application interface should have labels and text in the interface.

### Actual behaviour
Instead of labels and text, the templates are not being properly rendered. 
See image for further details:
![](https://cldup.com/qMKoHsz6ZJ.png)

### Server configuration
**Operating system**: Ubuntu 14.04.3 LTS

**Web server:** Apache/2.4.7 (Ubuntu)

**Database:** MySQL 5.5.47

**PHP version:** PHP 5.5.9

**ownCloud version:** ownCloud 8.2.2 (stable) 

**Updated from an older ownCloud or fresh install:** Updated

**List of activated apps:**

```
Enabled:
  - activity: 2.1.3
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - documents: 0.11.1
  - encryption: 1.1.0
  - external: 1.2
  - files: 1.2.0
  - files_antivirus: 0.8.0.0
  - files_locking:
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - music: 0.3.8
  - news: 7.1.0
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - tasks: 0.5.1
  - templateeditor: 0.1
  - updater: 0.6
Disabled:
  - files_external
  - search_lucene
  - user_external
  - user_ldap
  - user_webdavauth
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "[REDACTED]",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "[REDACTED]"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "[REDACTED]",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "no-reply",
        "mail_smtpmode": "sendmail",
        "mail_domain": "[REDACTED]",
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "logfile": "\/var\/log\/owncloud.log",
        "loglevel": 0,
        "logtimezone": "Europe\/Lisbon",
        "log_rotate_size": 52428800,
        "theme": "",
        "enable_previews": true,
        "preview_max_x": 512,
        "maintenance": false,
        "appstore.experimental.enabled": true,
        "trashbin_retention_obligation": "auto",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "asset-pipeline.enabled": true
    }
}
```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** No
 
### Client configuration
**Browser:** Google Chrome	48.0.2564.97 (Official Build) (64-bit)

**Operating system:** OS X (Yosemite) 10.10.5 (14F1605)

### Logs
No useful logs appear. I can provide anything specific that you request.

**Comment by Gomez** [comment]
Would you paste errors from the browser console?

The music app has a similar problem https://github.com/owncloud/music/issues/434

**Comment by Couto** [comment]
Unfortunately there are no errors in the browser's console while in the Tasks app.
I also get the reported errors on the music app, just like described in owncloud/music#434

**Comment by raimund-schluessler** [comment]
This was a problem with the minifier used in core. Should be good with https://github.com/owncloud/3rdparty/pull/266#issuecomment-208824525 now.
