### ISSUE TITLE
displaying and sorting tasks and subtasks

### ISSUE THREAD

**Issue by esaule** [owncloud/tasks#294]
It would be great if one could sort tasks using different criteria. Currently it seems like tasks are sorted based on priority, then deadline, then alphabetical.
It would be great to let the user chose the sorting order and add different criteria, for instance earliest due date (including subtasks recursively) would certainly be useful. Actually, even display the earliest due date of any subtasks (recursively) would be great too.

**Comment by raimund-schluessler** [comment]
With #357 the task list can now be sorted by the default order (duedate, priority, start, summary), by due date, by start date, by priority and alphabetically.
