### ISSUE TITLE
How to get the Tasks with caldav url

### ISSUE THREAD

**Issue by rashnk** [owncloud/tasks#299]
im using a caldav php library for this, calendars works fine, i want to get the Tasks also, What is the caldav url for Tasks,

**Comment by Henni** [comment]
It should be the same as for the calendar.

**Comment by rashnk** [comment]
/remote.php/caldav/calendar/admin/personal for my calendar
what should be the url for tasks ?
/remote.php/caldav/tasks/admin/personal  ?

**Comment by raimund-schluessler** [comment]
The url for the same calendar is the same for all apps as the calendar is handled by owncloud core. If it is ```/remote.php/caldav/calendar/admin/personal``` for calendar, then it is the same for tasks. However, calendars created with the Calendar app prior to https://github.com/owncloud/calendar/pull/408 do not support handling tasks, so they will likely not work.
