### ISSUE TITLE
Add support for catagories

### ISSUE THREAD

**Issue by requist** [owncloud/tasks#30]
Tasks Enhanced works great, especially with the smart collections. Probably already crossed the mind but what would, in my opinion, enhance the power of these smart collections greatly is the use of categories.

**Comment by raimund-schluessler** [comment]
First working implementation of categories can be found under https://github.com/owncloud/tasks/tree/ImplementCategories

Still some things to do:
- [ ] fetch available categories from the server
- [ ] style category area including icons for categories and delete button
- [ ] make sure select drop-down closes when clicking somewhere within the app
- [ ] remove unused css code

**Comment by raimund-schluessler** [comment]
Done with https://github.com/owncloud/tasks/pull/172
