### ISSUE TITLE
News tasks entered after OC auto-logout appear created (misleading)

### ISSUE THREAD

**Issue by fracture-point** [owncloud/tasks#300]
v 8.2.1 stable, MariabDB 10, php 5, apache

Steps to reproduce:

1. Log in to OC, navigate to Tasks.
2. Leave for a few hours (I believe OC defaults to a 1-hour logout policy)
3. Return - Tasks is still on the same screen...I'm not returned to the login screen
4. Create a task - it appears to save successfully and is added to the list!

The problem is, if I try to navigate elsewhere, I'm brought to the OC login screen because my session timed out.  The task that I created, in the meantime, failed to actually save due to the invalid session.  The user can't tell that the save was unsuccessful.

This is a problem for me, as I often run around to meetings, then say "Oh, right....I need to add this to the list so I don't forgot"...so I add something and then go on about my business, without realizing that my trusty-brain-replacer-task-app actually didn't save my reminder.

**Comment by raimund-schluessler** [comment]
This should be fixed with https://github.com/owncloud/tasks/pull/291

**Comment by raimund-schluessler** [comment]
Closing as it should be fixed in master now.
