### ISSUE TITLE
Short Description

### ISSUE THREAD

**Issue by aspdye** [owncloud/tasks#301]
Update short description of this repositroy to: :white_check_mark: Tasks app for ownCloud

**Comment by raimund-schluessler** [comment]
Good idea, but I think I am not allowed to do so (at least I don't see any button to change this).

@DeepDiver1975 Can you help out, please?

**Comment by aspdye** [comment]
Right. I've done this call for all the other Repositories and i think only members or admins of the org can change this :wink:
