### ISSUE TITLE
no entrys in Calendar and Tasks

### ISSUE THREAD

**Issue by Happyfeet01** [owncloud/tasks#303]
Hello, i updated to OC9 and the Calendar and Tasks App didn´t show any entry.

I can´t create an Calendar and i can´t also create an Task.

### Steps to reproduce
1. Install new Calendar for OC 9+
2. Try to add an calendar. 
3. Try to an Task

### Actual behaviour

The Calendar don't show any event.
I can't create any calendar. 

### Server configuration
**Operating system**:
Ubuntu 14.04 
**Web server:**
Apache 2.4.7
**Database:**
Mysql 14.14
**PHP version:**
5.5.9
**ownCloud version:** (see ownCloud admin page)
- installed: true 
- version: 9.0.0.19 
- versionstring: 9.0.0 
- edition: 

**Calendar version:** (see ownCloud apps page)
Version 1.0
**Updated from an older ownCloud or fresh install:**
Update from 8.2
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
Enabled: 
- activity: 2.2.1 
- calendar: true 
- comments: 0.2 
- contacts: true 
- dav: 0.1.5 
- documents: true 
- encryption: 1.2.0 
- fbsync: 1.8.2 
- federatedfilesharing: 0.1.0 
- federation: 0.0.4 
- files: 1.4.4 
- files_antivirus: 0.8.0.1 
- files_external: 0.5.2 
- files_pdfviewer: 0.8 
- files_sharing: 0.9.1 
- files_texteditor: 2.1 
- files_trashbin: 0.8.0 
- files_versions: 1.2.0 
- files_videoplayer: 0.9.8 
- firstrunwizard: 1.1 
- gallery: 14.5.0 
- hls_streamplayer: true 
- html5_videoplayer: true 
- music: true 
- news: true 
- notes: true 
- notifications: 0.2.3 
- ocdownloader: 1.5 
- provisioning_api: 0.4.1 
- shorten: 0.0.15 
- systemtags: 0.2 
- tasks: 0.9.0 
- templateeditor: 0.1 
- updatenotification: 0.1.0 
Disabled: 
- external 
- ownnote 
- user_external 
- user_ldap 
```

**The content of config/config.php:**

```
{ 
"system": { 
"instanceid": "ocpsovzwa7ww", 
"passwordsalt": "***REMOVED SENSITIVE VALUE***", 
"secret": "***REMOVED SENSITIVE VALUE***", 
"trusted_domains": [ 
"cloud-surfer.eu" 
], 
"memcache.local": "\\OC\\Memcache\\APCu", 
"memcache.distributed": "\\OC\\Memcache\\Memcached", 
"datadirectory": "\/mnt\/owncloud\/data", 
"overwrite.cli.url": "http:\/\/81.169.130.87\/", 
"dbtype": "mysql", 
"version": "9.0.0.19", 
"dbname": "owncloud", 
"dbhost": "localhost", 
"dbtableprefix": "oc_", 
"dbuser": "***REMOVED SENSITIVE VALUE***", 
"dbpassword": "***REMOVED SENSITIVE VALUE***", 
"logtimezone": "Europe\/Berlin", 
"installed": true, 
"loglevel": 3, 
"maintenance": false, 
"appstore.experimental.enabled": true, 
"singleuser": false, 
"mail_smtpmode": "php", 
"mail_from_address": "lars", 
"mail_domain": "cloud-surfer.eu", 
"mail_smtpauthtype": "PLAIN", 
"mail_smtpauth": 1, 
"mail_smtphost": "mail.cloud-surfer.eu", 
"mail_smtpport": "587", 
"mail_smtpname": "***REMOVED SENSITIVE VALUE***", 
"mail_smtppassword": "***REMOVED SENSITIVE VALUE***", 
"mail_smtpsecure": "ssl", 
"updatechecker": true, 
"theme": "" 
} 
} 
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration
**Browser:**
IE 11 (Chrome on Android)
**Operating system:**
Windows 7, Android 6.0.1
**CalDAV-clients:**
DAVdroid for Android

#### ownCloud log (data/owncloud.log)
```
Class 'OC_Calendar_App' not found at /var/www/vhosts/cloud-surfer.eu/httpdocs/owncloud/apps/tasks/controller/pagecontroller.php#60

```

**Comment by Henni** [comment]
@raimund-schluessler is currently working on the support for owncloud 9.0. Please check out the DAVclient branch, described in https://github.com/owncloud/tasks/pull/291

**Comment by Happyfeet01** [comment]
must i clean the calendar and Task Folder for this??

**Comment by Henni** [comment]
the old versions aren't supported in owncloud 9.0
Calendars and Tasks are stored in the database. So clearing the folders only removes the apps and not the data.

It sounds like you don't have to change anything for the calendar app. Just replace the current tasks app with the app from the DAVclient branch.

**Comment by raimund-schluessler** [comment]
You have to use the DAVclient branch. Your error ```Class 'OC_Calendar_App' not found``` shows, that you use Tasks 0.8 which does not support OC 9.
