### ISSUE TITLE
Shared task lists with DAVclient

### ISSUE THREAD

**Issue by Gerii** [owncloud/tasks#304]
I just installed the tasks app on my ownCloud test server. I tried to share a task list with another user with the edit permission activated (from the calendar app). When clicking on the list itself logged in as the user the list has been shared with, I can't add a task or edit it. When clicking on the Current or All tab I can create new tasks, but I still can't edit any of the existing ones.

### Server configuration
**Operating system**:
Raspbian
**Web server:**
Apache
**Database:**
PostgreSQL
**PHP version:**
5.6
**ownCloud version:**
9.0
**Updated from an older ownCloud or fresh install:**
8.2.2
**Where did you install ownCloud from:**
Repository

**Comment by raimund-schluessler** [comment]
Please check again with current master. Works fine for me.

**Comment by Gerii** [comment]
Seems to work now. Thanks!
