### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by ENDev15** [owncloud/tasks#307]
I have installed tasks on my in `/var/www/owncloud/apps` and changed the permissions to `0755` (same as default apps). However, when I go to the Tasks app in the web I am met with a completely blank page. 

I am running ownCloud 9 if that helps

Thanks.

**Comment by raimund-schluessler** [comment]
https://github.com/owncloud/tasks/issues/296

**Comment by ENDev15** [comment]
Thanks, @raimund-schluessler.
