### ISSUE TITLE
Installed with zip, app won't load with OC 9.0.1 (stable)

### ISSUE THREAD

**Issue by captainwasabi** [owncloud/tasks#308]
New installation.  Installed with the zip file. All other apps work fine.  When I try to run tasks it can't load the page and gives this error in the log:

   `Error	PHP	Class 'OC_Calendar_App' not found at /var/www/owncloud/apps/tasks/controller/pagecontroller.php#60`

The calendar is definitely loaded in is working.

**Comment by Henni** [comment]
Tasks for owncloud 9.0 is currently under development at https://github.com/owncloud/tasks/pull/291
Please checkout this branch.
