### ISSUE TITLE
issue with OC_Calendar_Calendar

### ISSUE THREAD

**Issue by suyashjain** [owncloud/tasks#309]
i have installed tasks and now i am getting the following error in apache error logs, 
 PHP Fatal error:  Class 'OC_Calendar_Calendar' not found in /opt/owncloud/apps/tasks/service/tasksservice.php on line 112 ,  i have already enabled the owncloud calendar.

**Comment by suyashjain** [comment]
when i am disabling the calendar app, it throws the error on UI that tasks can not be enabled as calendar app is disabled.

**Comment by raimund-schluessler** [comment]
https://github.com/owncloud/tasks/issues/296
