### ISSUE TITLE
handle done tasks the same way the task-app does

### ISSUE THREAD

**Issue by j20d** [owncloud/tasks#31]
There's a journal-app that is able to generate journal-entries based on tasks that have been marked as done.
If I mark a task as done using tasks_enhanced it is not recognized, but it shows up in tasks as done. If I modify it in tasks it shows up in the journal-app afterwards.

I have no idea where the difference in behaviour comes from, I looked at the task-objects in the database and did not see any difference.

I'll try to provide more information if I find any.

**Comment by raimund-schluessler** [comment]
I guess this issue is obsolescent. Correct me if I am wrong.
