### ISSUE TITLE
OC9: Tasks WebUI right pane empty, shows all tasks after click

### ISSUE THREAD

**Issue by valo-lindstroem** [owncloud/tasks#310]
When i switch to the tasks app in OC9, the lists are shown on the left, but the right pane is empty, no tasks are shown. When i make one click alle open tasks are shown on the right.

I'm on OC 9.0.2 and using the DAVclient branch from git on commit 8808e77
Tested with Browsers FF 46.0.1 and Chrome 50

**Comment by raimund-schluessler** [comment]
I can confirm this. It seems as the location url is not properly set at app startup. Will look into it.

**Comment by raimund-schluessler** [comment]
Fixed with https://github.com/owncloud/tasks/pull/291/commits/400cfb3de2bddd870490526eb2feac879476368a.

**Comment by valo-lindstroem** [comment]
Thanks.
Changed from git to the version from appstore and works fine.
