### ISSUE TITLE
Implement a search provider

### ISSUE THREAD

**Issue by raimund-schluessler** [owncloud/tasks#311]
Tasks should support the built-in search.

**Comment by GMTA** [comment]
Please note that as of OC 9.0.2 / tasks 0.9.0 the software contract of \OCP\Search\Provider is broken, breaking the entire OC search functionality.

At /controller/searchprovider.php the search($query) method returns nothing, but should instead return an empty array. Without this, the functionality in OC's /lib/private/search.php will break.

**Comment by raimund-schluessler** [comment]
@GMTA This problem is fixed in v0.9.1 of the Tasks app. Thanks for reporting!
