### ISSUE TITLE
Implement commenting on tasks

### ISSUE THREAD

**Issue by raimund-schluessler** [owncloud/tasks#315]
Use new owncloud comment support.

Also store comments in the VTODO? Migrate comments from VTODO to the OC comment backend?

**Comment by Paddo5819** [comment]
Is it possible to integrate, that url links are opened by klicking on it?

**Comment by raimund-schluessler** [comment]
Yes, should be no problem. This is already done for url in title and comments.

**Comment by Paddo5819** [comment]
Any suggestion when the commemt feature is implemented? That would be for our work the most important feature. I installed the 0,9 version atm and we are very impressed ☺

**Comment by uwecmyersjj** [comment]
Is the commenting features started at all? Is there anywhere we can see this in "action" so we can pick up the development?

**Comment by raimund-schluessler** [comment]
Depends on how you see it. Prior to Tasks v0.9 there was support for commenting. Some (maybe) useful remainders of the commenting feature are still in the code. Storing comments only in the VTODO should not be to much of a problem. Integrating with the oC commenting feature is more effort. However, I haven't started implementing this yet. Also, I think implementing sharing is more important, since commenting on a task that is only visible to you is not very useful.
