### ISSUE TITLE
Sharing of tasklists not possible when created from inside tasks

### ISSUE THREAD

**Issue by LollenJumplan** [owncloud/tasks#316]
### Steps to reproduce
1. Create a new tasklist from within tasks
2. Switch over to calendar

### Expected behaviour
It should show up, so I can share it.

### Actual behaviour
It doesn't show up, so I can't share it.

### Server configuration
**Operating system**: 
Debian testing with OBS stable repo (I know, but it seems to work fine)

**Web server:** 
Apache 2.4.18

**Database:**
mysql  Ver 14.14 Distrib 5.6.30, for debian-linux-gnu (i686) using  EditLine wrapper

**PHP version:**
PHP 7.0.5-3

**ownCloud version:** (see ownCloud admin page)
ownCloud 9.0.2

**Tasks version:** (see ownCloud apps page)
Newest after the big davclient merge (it says 0.9.0)

**Updated from an older ownCloud or fresh install:**
No

**Signing status (ownCloud 9.0 and above):**
No errors have been found.

**List of activated apps:**
Enabled:
  - activity: 2.2.1
  - announcementcenter: 1.1.2
  - calendar: 1.1
  - comments: 0.2
  - contacts: 1.2.0.0
  - dav: 0.1.6
  - documents: 0.12.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - ownnote: 1.08
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - tasks: 0.9.0
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

**Comment by raimund-schluessler** [comment]
That the list does not show up on the calendar is the intended behaviour as discussed here: https://github.com/owncloud/tasks/issues/298#issuecomment-198731564.

In the future it will be possible to share a list from within the Tasks app. For now, please create the list in the Calendar app if you want to share it.

**Comment by LollenJumplan** [comment]
Okay, I understand, sorry for bothering then.

**Comment by raimund-schluessler** [comment]
No problem. Sharing tasks is tracked in https://github.com/owncloud/tasks/issues/47.
