### ISSUE TITLE
Allow task list sorting in the left sidebar

### ISSUE THREAD

**Issue by kas70** [owncloud/tasks#318]

**Comment by sahne123** [comment]
There is an issue for sorting calendars at the calendar app https://github.com/owncloud/calendar/issues/133.  Question is: do we need a custom sorting in the task app?

**Comment by raimund-schluessler** [comment]
We could do that. Should not be too hard to implement a drag and drop sort option with the already used draganddrop library https://github.com/owncloud/tasks/tree/master/js/vendor/angular-draganddrop
