### ISSUE TITLE
Placeholder labels after upgrade to OC 9.0.2

### ISSUE THREAD

**Issue by okulev** [owncloud/tasks#319]
I upgraded my ownCloud 8.2 to latest 9.0.2 and Tasks stopped working. Today I deleted apps/tasks/ directory and git cloned the tasks app. After enabling I went to Tasks and localization placeholders are not replaced with text. Screenshot is attached. There aren't any log messages to report.

![screenshot from 2016-05-29 - tasks](https://cloud.githubusercontent.com/assets/842059/15633004/024fdd0e-25ab-11e6-93cc-5240e9be01c6.png)

**Comment by raimund-schluessler** [comment]
First of all: There is an issue template and its there for a reason.

You did not install the app correctly. Either some files are missing or the permissions are not set correctly. Also, the official way of installing apps is by installing via the appstore. Don't install via git unless you know what you are doing.
