### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by Jonny007-MKD** [owncloud/tasks#32]
Hi,
I'm running tasks in current OC 6.0.3. This is the error I get when the Web UI is trying to load the tasks:

> PHP Fatal error:  Call to a member function getAsString() on a non-object in /var/www/vhost/apps/tasks/lib/app.php on line 49

Seems like $vtodo is no object.

> public static function arrayForJSON($id, $vtodo, $user_timezone)
>     {
>                 $task = array( 'id' => $id );
> $task['summary'] = $vtodo->getAsString('SUMMARY');

**Comment by raimund-schluessler** [comment]
This should be fixed with moving the CalDAV stuff to owncloud core already.
