### ISSUE TITLE
Tasks - extended to be used as project management tool

### ISSUE THREAD

**Issue by hitam4450** [owncloud/tasks#320]
Feature request:
Since OwnCloud enables and supports users to work in a "**distributed**" & "**shared**" environment,  
the next logical step would be to combine the calendar & tasks app into a  classical 
"**Project Management**" app, including :
        _Scheduling
        Critical path
        Cost accounting
        Reporting
        Presentation, etc._
Perhaps an existing tool (or parts of it) could be modified, integrated and extended to meet OC requirements !
Creating a new project  "**Project Management**"  would be another possible solution!
I am looking forward to discussing this issue!
regards, hitam4450

**Comment by ccoenen** [comment]
Tasks and Project Management Tools solve a similar problem in the same way that Bicycles and Planes solve the similar problem (transportation). I do not think it is wise to make tasks a project management tool. One of the reasons is, that project management is a very diverse field. Pretty much everyone has different use cases, wants different functionalities, needs different views into a PM system.

I also think this is very far outside of what the iCalendar / CalDAV / VTODO standard can deliver, so you'd have to store everything in your own `X-blabla-` fields in your VTODO, which would probably be inefficient to query or you'd have to put it all in the database, but then you'll only have access to it on the web (not synced to a CalDAV client).

I believe these two should be separate projects.
