### ISSUE TITLE
Tasks not working since ownCloud 8.2.5

### ISSUE THREAD

**Issue by Pempam** [owncloud/tasks#321]
After activating:

"The Archive doesn't contain a directory with the name tasks"

After manual installation (Version 0.8.1.):

"The application directory exists already"

:-(

**Comment by RealRancor** [comment]
@raimund-schluessler The issue here is that you're linking the downloads for e.g. 8.2 on:

https://apps.owncloud.com/content/show.php/Tasks?content=164356

to:

https://github.com/owncloud/tasks/archive/v0.8.1.zip

Those archives are containing the version number within them like:

tasks-0.8.1

where oC is only expecting a folder called:

tasks

**Comment by raimund-schluessler** [comment]
@RealRancor Thanks for pointing out the problem. I will try to link to correct zip archives.

**Comment by RealRancor** [comment]
@raimund-schluessler The oC 9 release (0.9.1) was also already correctly released https://github.com/owncloud/tasks/releases/download/v0.9.1/tasks.zip so its probably just a matter of attaching the archives with the correct structure to each of the releases at https://github.com/owncloud/tasks/releases and linking to them from the appstore.

**Comment by raimund-schluessler** [comment]
Yes, I manually uploaded this this zip-file (https://github.com/owncloud/tasks/releases/download/v0.9.1/tasks.zip) to Github. I will do this for the older releases too (at least for the last releases for oC 8 and 7).

**Comment by raimund-schluessler** [comment]
I uploaded the zip files to github and linked them in the appstore. I hope this fixes your issues with installing the app. Please report if so.

**Comment by raimund-schluessler** [comment]
I consider this fixed. Please reopen if it is still not working.
