### ISSUE TITLE
how to assign task to specific calendar

### ISSUE THREAD

**Issue by pcause** [owncloud/tasks#322]
I don't see a way to assign a task to a specific calendar.  Different calendars have different caldav URLs.   Is there a way to do this?  Which calendar does the task get assigned to?  Can you update the readme.md?

**Comment by raimund-schluessler** [comment]
I don't really understand what you are talking about. A newly created task is created in the calendar you select on the left side. It is written in the input field, see the screenshot for example:
https://cloud.githubusercontent.com/assets/2496460/9783697/ab337634-57a6-11e5-9633-b8f950b1e28e.png

The task will be created in "Default calendar". When you select a different calendar on the left, it would be created in e.g. "Astronomy". You can also drag and drop tasks to a certain calendar.

**Comment by pcause** [comment]
I don't see any calendars on the left side, just task lists

![octasks](https://cloud.githubusercontent.com/assets/1071479/16563924/be522802-41d2-11e6-9055-1c4194c59eab.png)

**Comment by raimund-schluessler** [comment]
"phil personal" and "nextcloud-tasks" are calendars too. It depends on where you created these calendars. In https://github.com/owncloud/tasks/issues/298#issuecomment-198731564 we came to the consensus, that a calendar/list created in the Tasks app should not show up in the Calendar app, but calendars/lists created in the Tasks app will show up in both apps. If you created a calendar in the Calendar app, it should show up in the Tasks app.

**Comment by pcause** [comment]
thanks

**Comment by raimund-schluessler** [comment]
Does it work as expected now?

**Comment by pcause** [comment]
yes and thanks.  i was also able to syn with thunderbird using caldav so it is great.
