### ISSUE TITLE
Installing Bad Request

### ISSUE THREAD

**Issue by jedjann** [owncloud/tasks#323]
hi i got this when i enable the tasks.

ive done the git clone or manual extract to apps folder but same result

ive tried the link 
https://apps.owncloud.com/CONTENT/content-files/164356-tasks.zip
https://github.com/owncloud/tasks/archive/master.zip
https://github.com/owncloud/tasks/releases/download/v0.9.1/tasks.zip
https://github.com/owncloud/tasks/releases/download/v0.9.0/tasks.zip

![image](https://cloud.githubusercontent.com/assets/17632951/16578038/fa6b138c-42ca-11e6-92a3-39efd73fd928.png)

fresh install owncloud 9.0.2
tasks v0.9.1

centos 7.2.1511(core)
apache 2.4.6-40.el7.centos.1
5.5.47-MariaDB 
5.4.16-36.el7_2.1 php

Thanks!

**Comment by milesgillham** [comment]
+1 Pretty much the same environment (except PHP 5.56 and trying to upgrade from 0.9.0 to 0.9.1) and same error result. All other apps upgrading fine, just Tasks with this error.

**Comment by jedjann** [comment]
hi miles 
i just figure it out the bug. 
just go to APPS >> click NOT ENABLE >> find the TASKS and click ENABLE. 
mine is running now

**Comment by milesgillham** [comment]
Cool, thank you! Will try it out.

Regards, Miles
---

**Comment by RealRancor** [comment]
There is now an open issue in core about this: https://github.com/owncloud/core/issues/25541
