### ISSUE TITLE
Release tasks with valid certificate

### ISSUE THREAD

**Issue by RealRancor** [owncloud/tasks#328]
Once people updating to oC 9.0.4 the following is shown in the admin backend:

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- tasks
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate has been revoked.

Raw output
==========
Array
(
    [tasks] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Certificate has been revoked.
                )

        )

)
```

In https://github.com/owncloud/appstore-issues/issues/62 the cert of the 0.9.1 version was revoked. Please re-upload a new tasks version with a valid certificate.

**Comment by JB1985** [comment]
Same if I want to install the App

Error:
Die Signatur konnte nicht überprüft werden. Bitte kontaktiere die App-Entwickler und überprüfe deinen Admin-Bildschirm.

**Comment by fracture-point** [comment]
Got the same error on 9.0.4 upgrade from 9.0.3.  

Now I cannot create a new task in the UI (typing in the box "Add an item" does not show any text as I type).  I can still view my old tasks.

**Comment by jas4711** [comment]
I just upgraded to 9.0.4 and see the same issue.  I have no problem using the app though, creating tasks in the UI works fine for me.

**Comment by raimund-schluessler** [comment]
The missing certificate should not affect the UI. If it does, something else is broken I guess.
However, I will release a version with a correct certificate soon.

**Comment by jedjann** [comment]
same problem but my tasks app is working fine after the upgrade to 9.0.4 but getting the "Certificate has been revoked" error

**Comment by JB1985** [comment]
On oc9.1 same error!

**Comment by RealRancor** [comment]
@JB1985 As long as no new version of the tasks app is released you will get the same error with ownCloud 15

**Comment by pbek** [comment]
I have the same problem, `Certificate has been revoked`. ;)

**Comment by Pazu** [comment]
Please note the problem is confirmed, and no additional "me, too" reports are needed at this time.

**Comment by raimund-schluessler** [comment]
The release https://github.com/owncloud/tasks/releases/tag/v0.9.2 now fixes this issue.
