### ISSUE TITLE
Wrong task list colour if created with DavDroid on Android

### ISSUE THREAD

**Issue by Gerii** [owncloud/tasks#329]
### Steps to reproduce
1. Create a calendar with task support with DavDroid on Android, choose a colour other than red
2. Open tasks app in web interface
3. Look at list colour

### Expected behaviour
Web interface should show the same colour as chosen in the app (just like the calendar app does)

### Actual behaviour
All calendars created with DavDroid have a red colour in the tasks app

### Server configuration
**ownCloud version:** (see ownCloud admin page)
9.0.4
**Tasks version:** (see ownCloud apps page)
0.9.1
**Updated from an older ownCloud or fresh install:**
Updated from 9.0.x

### Client configuration
**CalDAV-clients:**
DavDroid

**Comment by raimund-schluessler** [comment]
The Tasks app loads the color from owncloud core via a normal CalDAV request. If the correct color is not shown, this means it is never saved in the database. So it's either an issue of the CalDAV server in owncloud core or the DavDroid app. Please report this issue in the respective repository: https://github.com/owncloud/core

**Comment by Gerii** [comment]
I'm not sure if this is a core issue, as the calendar app is handling it correctly. I tried to debug the issue and I found out that in the tasks app the calendar.color variable contains the alpha value, while in the calendar app it does not. (#752BA1FF vs. #752BA1)
I did not find out where the calendar variable is coming from in both apps, so I couldn't dig further.

**Comment by raimund-schluessler** [comment]
This means the variable is saved and updated in the database, it only contains the alpha value? Then we could handle it in the app.

**Comment by Gerii** [comment]
Yes, exactly.

**Comment by raimund-schluessler** [comment]
Calendar had the same issue. https://github.com/owncloud/calendar/pull/387 We just need to cut off the alpha value.
