### ISSUE TITLE
Certificate has been revoked

### ISSUE THREAD

**Issue by enoch85** [owncloud/tasks#333]
### Steps to reproduce
1. Run intergity check

### Expected behaviour
No errors

### Actual behaviour
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- tasks
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate has been revoked.
```

### Server configuration
**Operating system**:
Ubuntu 16.04
**Web server:**
Apache 2.4
**Database:**
MySQL 5.7
**PHP version:**
7
**ownCloud version:** (see ownCloud admin page)
9.1
**Tasks version:** (see ownCloud apps page)
0.9.1

**Comment by raimund-schluessler** [comment]
Please see #328.

**Comment by RealRancor** [comment]
@raimund-schluessler As https://github.com/owncloud/tasks/issues/328 is locked i'm just giving the feedback here:

Just updated tasks from 0.9.1 to 0.9.2 on oC 9.0.4 without any issues and the integrity message is also gone. Thank you very much for this release. Keep up the good work :+1:

**Comment by raimund-schluessler** [comment]
Thanks for the feedback, good to hear :smiley:

**Comment by Basti1512** [comment]
Old (previously fixed) bug, but now I've got it back on my system:

**Operating system:**
Ubuntu 16.04
**Web server:**
Apache 2.4.18-2ubuntu3.5
**Database:**
MySQL 5.7
**PHP version:**
7
**ownCloud version:** (see ownCloud admin page)
10.0.6.1
**Tasks version:** (see ownCloud apps page)
0.9.4

**Comment by dlandon** [comment]
The latest signed version is 0.9.3 that I updated on the Marketplace.  The 0.9.4 certificate has been revoked because I am now signing the app.  Uninstall the 0.9.4 version and install the 0.9.3 version from the Marketplace.
