### ISSUE TITLE
Shade top-level tasks differently

### ISSUE THREAD

**Issue by olantrust** [owncloud/tasks#335]
Top level tasks should be shaded lightly, so that visually the User can swiftly distinguish them from child tasks, when dealing with a lot of tasks.

Steps:
A long list of tasks with multiple parent and child tasks is viewed.

Expected:
The user can visually differentiate easily between top-level tasks (their main task list) and child tasks. (Indentation not alone being sufficient.)

Actual:
Only indentation differentiates, this can cause problems, particularly with people who have a lot of tasks, or who are dyslexic.

Resolution:
Top levels tasks are very lightly shaded, all other tasks remain white.
Currently, the task which is presently open is highlighted, so a different type of highlighting would be required. Or, for clarity, the presently open task could be outlined instead.

**Comment by ccoenen** [comment]
not shure if this warrants a separate issue, but it would also be very helpful to have a "collapse all" or "expand all" function somewhere. Going over a large list, I find myself frequently checking all those tiny "collapse" buttons one-by-one.
