### ISSUE TITLE
Remove lines in description field

### ISSUE THREAD

**Issue by olantrust** [owncloud/tasks#336]
Currently the task panel has a shaded area for the task description.
This area also is lined.
Some Users will not want the distraction of lines in that area.
An option to turn those off would be practical.

**Comment by raimund-schluessler** [comment]
We will definitly not introduce an option for every design detail.

However, we can discuss if these lines are necessary at all or if we can reduce the skeuomorphism.
@jancborchardt What do you tink?

**Comment by olantrust** [comment]
I agree about the change. I see the design reason for the lines, but I think ultimately it's a bit inconsistent with the rest of the interface, including similar panels for Calendar events etc...

**Comment by jancborchardt** [comment]
@olantrust has a good point about the slight inconsistency with other interface parts, so I agree it would be better to remove the lines. :)

**Comment by raimund-schluessler** [comment]
I removed the lines. Will be in the next release.

**Comment by jancborchardt** [comment]
Good stuff! :)
