### ISSUE TITLE
Tasks not showing in IE11 and Microsoft Edge

### ISSUE THREAD

**Issue by Dennis1993** [owncloud/tasks#341]
### Steps to reproduce
1. install a fresh owncloud 9.1.0
2. activate the tasks app
3. insert a new Task
4. refresh the page and all entries not shown

### Expected behaviour
Show me my tasks

### Actual behaviour
Tasks not shown

### Server configuration
**Operating system**:
Apache 2.4

**Web server:**
all-inkl.com

**Database:**
MySQL 5.6

**PHP version:**
7.0.8

**ownCloud version:** (see ownCloud admin page)
9.1.0

**Updated from an older ownCloud or fresh install:**
fresh installation

**Where did you install ownCloud from:**
owncloud

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```

**List of activated apps:**
 Deleted files 
 Mail Template Editor 
Notifications
 PDF Viewer 
 Share Files 
 Text Editor 
 Update notification 
Versions
 Video player 
Calendar
Tasks

**The content of config/config.php:**
Default, no changes!

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
IE11, Edge
With Firefox it works and Safari on iPhone with iOS 9.3.3

**Operating system:**
Windows 10 and iOS

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Exception: {"Message":"HTTP\/1.1 415 Unsupported Media Type","Exception":"Sabre\\DAV\\Exception\\ReportNotSupported","Code":0,"Trace":"#0 [internal function]: Sabre\\DAV\\CorePlugin->httpReport(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/www\/htdocs\/cloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/www\/htdocs\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:REPORT', Array)\n#3 \/www\/htdocs\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/www\/htdocs\/cloud\/apps\/dav\/lib\/Server.php(169): Sabre\\DAV\\Server->exec()\n#5 \/www\/htdocs\/cloud\/apps\/dav\/appinfo\/v2\/remote.php(29): OCA\\DAV\\Server->exec()\n#6 \/www\/htdocs\/cloud\/remote.php(164): require_once('\/www\/htdocs\/clo...')\n#7 {main}","File":"\/www\/htdocs\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","Line":719,"User":"Dennis1993"}

XMLReader::XML(): Empty string supplied as input at /www/htdocs/cloud/3rdparty/sabre/xml/lib/Service.php#116
```

![unbenannt](https://cloud.githubusercontent.com/assets/1473674/17225618/0471d1e8-5506-11e6-8615-718d9a507b94.PNG)

**Comment by raimund-schluessler** [comment]
Sorry to say that, but IE and Edge are not supported. Please see https://github.com/owncloud/calendar/issues/309 for the reasons.

**Comment by Dennis1993** [comment]
> Sorry to say that, but IE and Edge are not supported.

Okay... That's not professional. Then I use another software but thanks!
In my opinion is the Microsoft Edge a must have for OwnCloud. I understand that IE is not supported but Edge?

Thanks for your answer.

**Comment by raimund-schluessler** [comment]
Have you thought about using another browser (software)? ;)

Professional or not is not the question. The Tasks app is a freetime project (and I am the only one working on it). I don't use Edge or IE at all. Also developing for Edge is a pain in the ***. It doesn't even let me access my development environment, because it runs in the local network. To be honest, for me it would be a waste of time working with these browsers. The best would be to needle Microsoft until they implement the missing features.

Afaik owncloud itself supports IE and Edge, but it is their job to make it work (and they are paid for it by their customers).

**Comment by Dennis1993** [comment]
So many products says: "Use IE11, use Firefox, use Chrome..., we don't support browser XY"
I'm an end user. I've installed **5 browsers** to use all software. It can not be true. It's not meant to be mean. But as end user annoys... 👎

If I'm surfing, I must start 4 browsers to use all websites without problems. I won't use Firefox because it is slowly, Chrome is from Google and I can't trust Google. Safari can't display all websites without problems, Edge is very fast but owncloud doen't work fine. I hate it.

Why not they'll agree on a standard?

I look for another product now. I can't install many browsers on different PC. If I'm in school, I can't install browsers to use owncloud. Same at work. I can't install browsers on this PC.
Owncloud is a CLOUD to use it from all places on the world. But if I must install different browsers to use it... no way.

In my opinion it is the best way to support Microsoft Edge, because this browser is installed on ALL new computers with Windows. Firefox, Safari or Chrome are not installed on all PCs. If I'm not on my PC I can't use owncloud. Then I need not ownCloud.

Sorry but thanks!

**Comment by raimund-schluessler** [comment]
Not everybody uses Windows and I would rather trust Google than Microsoft. Also there is an OpenSource alternative of Chrome with not Google at all: Chromium.

However, I understand your frustration, but it is a problem of the Browser vendors and not of single Webdevelopers. Because as a developer I have the same problem as you have as a user: I cannot test every single browser out there.

**Comment by dper** [comment]
@Dennis1993 If you're looking for a workaround, use [Firefox Portable](http://portableapps.com/apps/internet/firefox_portable). Put it on your USB thumb drive. No need to install anything ever again.

**Comment by Dennis1993** [comment]
@dper thanks but USB ports are motly blocked. :-( But thanks!

**Comment by olantrust** [comment]
@Dennis1993 I think the idea is that other contributors and users, could make it work with Edge, if they want to (as this is open source, and any of us is welcome to contribute ourselves if its reasonable). Perhaps others can collaborate on that somewhere and figure out what's needed?

**Comment by RealRancor** [comment]
@Dennis1993 Yeah, ranting at a free time developer instead of understanding that this is a general problem of the browser mess this days is always a good idea.

Btw. as already stated above oC works with Edge
