### ISSUE TITLE
CREATED, DTSTAMP, LAST-MODIFIED not stored as UTC

### ISSUE THREAD

**Issue by renatofilho** [owncloud/tasks#342]
### Steps to reproduce
1. Create a new event
2. Save the calendar in a file
3. Open the file and check LAST-MODIFIED field
### Expected behaviour

LAST-MODIFIED field should contains the tz information something like: 20060102T150405Z
### Actual behaviour

LAST-MODIFIED is stored without tz information something like: 20060102T150405
### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
apache

**Database:**
mysql

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
ownCloud 9.1.0 (stable)

**Tasks version:** (see ownCloud apps page)
 Calendar 1.3.1

**Updated from an older ownCloud or fresh install:**
fresh install

**Signing status (ownCloud 9.0 and above):**
No errors have been found.

**List of activated apps:**
Enabled:
- activity: 2.3.2
- calendar: 1.3.1
- comments: 0.3.0
- contacts: 1.3.1.0
- dav: 0.2.5
- encryption: 1.3.0
- federatedfilesharing: 0.3.0
- federation: 0.1.0
- files: 1.5.1
- files_pdfviewer: 0.8.1
- files_sharing: 0.10.0
- files_texteditor: 2.1
- files_trashbin: 0.9.0
- files_versions: 1.3.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- gallery: 15.0.0
- notifications: 0.3.0
- provisioning_api: 0.5.0
- systemtags: 0.3.0
- templateeditor: 0.1
- updatenotification: 0.2.1
  Disabled:
- external
- files_antivirus
- files_external
- user_external
- user_ldap

**The content of config/config.php:**

{
    "system": {
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "secret": "**_REMOVED SENSITIVE VALUE**_",
        "trusted_domains": [
            "localhost",
            "192.168.1.123"
        ],
        "datadirectory": "\/home\/ocdata",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "9.1.0.15",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "**_REMOVED SENSITIVE VALUE**_",
        "dbpassword": "**_REMOVED SENSITIVE VALUE**_",
        "logtimezone": "UTC",
        "installed": true,
        "instanceid": "oc56vcdmfuw8"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
NO

**Are you using encryption:** yes/no
NO

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO
### Client configuration

**Browser:**
firefox

**Operating system:**
Ubuntu 16.04

**CalDAV-clients:**
syncevolution

**Comment by renatofilho** [comment]
I noticed that "LAST-MODIFIED" is not getting update if you edit a event.

**Comment by raimund-schluessler** [comment]
Thanks for the report. Sadly the timezone support for the Tasks app is not really available. It lacks support for timezones for DTSTART, DUE and every other datetime. This has to be implemented yet, I will create a separate issue regarding this.

However, I am not completely sure if it is necessary for the LAST-MODIFIED property to contain a timezone, but I guess you are right. Maybe  @georgehrke can give a hint if it is necessary for the LAST-MODIFIED to contain the "Z" for UTC? If its the case, I guess CREATED should contain a "Z" too.

Also that the property is not updated has to be fixed too. I will also create an issue for this.

**Comment by georgehrke** [comment]
see https://github.com/owncloud/calendar/issues/657

**Comment by raimund-schluessler** [comment]
With 5f7f50a163e326dd5cb8ecd43205e2ed48976314 the ```last-modified``` property is updated on every edit of an event.

Timezone problem still needs to be solved.

**Comment by raimund-schluessler** [comment]
See https://github.com/mozilla-comm/ical.js/issues/260 for upstream issue.
