### ISSUE TITLE
Disable "Contact Birthdays" in Tasks UI, add setting for default task list

### ISSUE THREAD

**Issue by fracture-point** [owncloud/tasks#343]
OC 9.1.0, Tasks 0.9.2.

Despite having multiple calendars / task lists, the UI always defaults to Contact Birthdays, which is a non sequitur, given that it is read-only.  Quickly typing in a new task and hitting enter just clears the box (as though the task was created), but of course it was not, because the UI tries to jam it into the Contact Birthdays list.

![image](https://cloud.githubusercontent.com/assets/410707/17298534/559cfad2-57d8-11e6-892f-729a0873b75e.png)

The Contact Birthdays calendar should be suppressed completely from the UI, and I would recommend adding a setting to choose the default task list for new tasks.

**Comment by fracture-point** [comment]
Ah, just noticed the recently closed ticket that tackles this:
https://github.com/owncloud/tasks/issues/338

Please close this enhancement.

**Comment by raimund-schluessler** [comment]
No problem, the birthday calendar should be hidden once https://github.com/owncloud/core/pull/25636 is in.
