### ISSUE TITLE
Can't delete tasks

### ISSUE THREAD

**Issue by gtozzi** [owncloud/tasks#344]
Hi there!

First of all, thank you for developing and sharing this app!

### Steps to reproduce
1. Create a task by mistake
2. Try to delete it just after creating it
3. No "delete" option can be found

### Expected behavior
I was expecting to find a delete button

### Actual behavior
It looks like there is no delete button at all, or it is very well hidden.
A possible workaround is to "recycle" the task but assigning it a new name.

### Client configuration
Firefox latest

**Comment by raimund-schluessler** [comment]
You have to open the details of the task by clicking at it. The delete button is located at the bottom left of the details view.

**Comment by olantrust** [comment]
It would be useful when managing or sorting a large number of tasks to delete multiple items at once - for example when #22 is resolved.

**Comment by gtozzi** [comment]
I swear I've been accurately searching for it multiple times :)

Maybe it should just be an option in the details view, like priority or dates are.
Or maybe it's just me ;)

In both cases, thank you for your answer, @raimund-schluessler
