### ISSUE TITLE
Automatically open new task after creation

### ISSUE THREAD

**Issue by korelstar** [owncloud/tasks#350]
(Enhancement)

It would be nice, if the sidebar on the right side opens automatically, if a new task was created using the input field on the top. Then, you can add more attributes like due dates or descriptions, which is often needed. Currently, you have to search for the new task in the (sometimes very long) list of tasks before being able to add more attributes to the new task.

**Comment by raimund-schluessler** [comment]
Sounds reasonable. Will have a look at your PR.
