### ISSUE TITLE
Deleted items folder

### ISSUE THREAD

**Issue by olantrust** [owncloud/tasks#355]
Tasks app should have a deleted items folder, working in the same way as the Files app, with a 'Deleted items' link displaying in the left-hand bar, above the Settings link.

Deletion would become a two step process, deleted items would move to that folder, and then be permanently removed if the folder was emptied, or an individual items was deleted from within the folder.

Items could also be restored from the folder to their original location.

Is is the expected behaviour that most Uses are used to in other software managing contacts (including iOS, Android, Zimbra, Outlook, Google etc....

It is more useful than the current behaviour and mitigates against unintended data loss which can be catastrophic.

**Comment by raimund-schluessler** [comment]
I will have a look how https://github.com/owncloud/calendar/issues/253 turns out first.

**Comment by mar1u5** [comment]
👎 from `calendar`-side. What about an undo-button for tasks? 😁 @raimund-schluessler

**Comment by raimund-schluessler** [comment]
This is what my previous post is referring to.
