### ISSUE TITLE
Feature Proposal: Default time for "start date" and "due date"

### ISSUE THREAD

**Issue by ccoenen** [owncloud/tasks#367]
In my workflow, the **time** is usually not something of great importance. Certainly not in 5 minute increments. I regularly default to the same few times:
- around the time I get out of the door
- around the time I take a longer break
- around the time I come home
- around the [time you can expect to successfully (and non-intrusively) call somebody at home in the evening](https://xkcd.com/1335/).

These times would have to be a user-setting in my opinion.

Also, for due **dates**, I would love these three extra choices:
- TODAY
- tomorrow
- current due date +1 day (basically just an increment button for the usual quick _naaah i'll totally do THAT one tomorrow_)

For my workflow, having a choice of 4-5 default times at the top of the timepicker would make this so much easier.

**Comment by dlandon** [comment]
Please try the new version once uploaded to the Marketplace and report back with issues.
