### ISSUE TITLE
Feature Proposal: Custom Filters / Views

### ISSUE THREAD

**Issue by ccoenen** [owncloud/tasks#368]
Right now, you can view these things from the left menu:
- Important
- Today
- This Week
- All
- Current
- Done
- (and then a list of calendars / lists)

Is there any possibility to customize the smart collections? For one thing, having "today" combined with any of the lists would be super helpful in case you have many long lists. But doing your own query would be super neat. Things like this `categorized as work AND completed > 50%` (made up example, but you get the point).

**Comment by dlandon** [comment]
Please try the new version once uploaded to the Marketplace and report back with issues.
