### ISSUE TITLE
Include location field

### ISSUE THREAD

**Issue by olantrust** [owncloud/tasks#371]
Steps to reproduce:
1. Create new task
2. Open detailed pane

Expected behaviour:
User expects to be able to enter a location for that task to assist with managing tasks at different locations, and help those doing the task.

Actual behaviour:
No location field is available.

Proposed solution:
Have a location field.
If preferred, there could be a configurable option to hide this field (or alternatively hide it by default and have an option to show this).

Server configuration:
ownCloud version: 9.1
Tasks version: 0.9.3

**Comment by dlandon** [comment]
Please try the new version once uploaded to the Marketplace and report back with issues.
