### ISSUE TITLE
Status field

### ISSUE THREAD

**Issue by olantrust** [owncloud/tasks#372]
Steps to reproduce:
1. Create new task
2. Open detailed pane

Expected behaviour:
User expects to be able to set the status of a task for 
a) easy management of lots of tasks to see where they are all at
b) ability to see instantly what the status of an individual task is

Actual behaviour:
No status field is available, only a % percentage progress. Which is useful, but doesn't meet the needs of working out a task's status.

Proposed solution:
Have a Status field.

Implementation:
- Choices for status field: 1) Proposed [awaiting confirmation] 2) Not started 3) In progress 4) Awaiting input [i.e. from an event or another use] 5) Deferred 6) Completed 
- Automation: a User could benefit from the status field, without ever changing it manually, it would still help in their organisation of tasks.
Status 2) would be the default status when a task was created
Status 3) would be set automatically when a % progress was set
Status 6) would be set automatically when a task was marked completed
- If preferred, there could be a configurable option to hide this field (or alternatively hide it by default and have an option to show this).

Server configuration:
OwnCloud version: 9.1
Tasks version: 0.9.3

**Comment by dlandon** [comment]
Please try the new version once uploaded to the Marketplace and report back with issues.
