### ISSUE TITLE
add new list does not work

### ISSUE THREAD

**Issue by mraict** [owncloud/tasks#375]
I click on add list
and type new list name
and save

new list must be created and shown

but nothing happens

linux
apache
mysql 5.6.33
php 5.4.45

ownCloud 9.1.2 (stable)
Tasks 0.9.3
ownCloud  fresh install

Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 

No errors have been found.

**List of activated apps:**
files, activity, documents, gallery, contacts, bookmarks, ...

**The content of config/config.php:**
$CONFIG = array (
  'instanceid' => 'ocxqzjdjqj8z',
  'passwordsalt' => ' ',
  'secret' => ' ',
  'trusted_domains' => 
  array (
    0 => 'oc.segalesh.com',
  ),
  'datadirectory' => '/home/segale/domains/segalesh.com/public_html/oc/data',
  'overwrite.cli.url' => 'http://oc.segalesh.com',
  'dbtype' => 'mysql',
  'version' => '9.1.2.5',
  'dbname' => 'segale_oc',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'segale_oc',
  'dbpassword' => ' ',
  'logtimezone' => 'UTC',
  'installed' => true,
  'appstore.experimental.enabled' => false,

**Are you using encryption:** no

#### ownCloud log (data/owncloud.log)
Log
Error 	PHP 	Symfony\Component\Routing\Exception\InvalidParameterException: Parameter "rel_path" for route "collaboration_route" must match "[^/]++" ("" given) to generate a corresponding URL. at /home/segale/domains/segalesh.com/public_html/oc/3rdparty/symfony/routing/Generator/UrlGenerator.php#177 	2016-12-12T10:38:08+00:00
Error 	index 	Exception: {"Exception":"Symfony\\Component\\Routing\\Exception\\InvalidParameterException","Message":"Parameter \"rel_path\" for route \"collaboration_route\" must match \"[^\/]++\" (\"\" given) to generate a corresponding URL.","Code":0,"Trace":"#0 \/home\/segale\/domains\/segalesh.com\/public_html\/oc\/3rdparty\/symfony\/routing\/Generator\/UrlGenerator.php(136): Symfony\\Component\\Routing\\Generator\\UrlGenerator->doGenerate(Array, Array, Array, Array, Array, 'collaboration_r...', 1, Array, Array)\n#1 \/home\/segale\/domains\/segalesh.com\/public_html\/oc\/lib\/private\/Route\/Router.php(320): Symfony\\Component\\Routing\\Generator\\UrlGenerator->generate('collaboration_r...', Array, 1)\n#2 \/home\/segale\/domains\/segalesh.com\/public_html\/oc\/lib\/private\/URLGenerator.php(67): OC\\Route\\Router->generate('collaboration_r...', Array)\n#3 \/home\/segale\/domains\/segalesh.com\/public_html\/oc\/lib\/public\/Util.php(321): OC\\URLGenerator->linkToRoute('collaboration_r...', Array)\n#4 \/home\/segale\/domains\/segalesh.com\/public_html\/oc\/apps\/collaboration\/appinfo\/app.php(28): OCP\\Util::linkToRoute('collaboration_r...', Array)\n#5 \/home\/segale\/domains\/segalesh.com\/public_html\/oc\/lib\/private\/legacy\/app.php(187): require_once('\/home\/segale\/do...')\n#6 \/home\/segale\/domains\/segalesh.com\/public_html\/oc\/lib\/private\/legacy\/app.php(150): OC_App::requireAppFile('collaboration')\n#7 \/home\/segale\/domains\/segalesh.com\/public_html\/oc\/lib\/private\/legacy\/app.php(120): OC_App::loadApp('collaboration')\n#8 \/home\/segale\/domains\/segalesh.com\/public_html\/oc\/lib\/base.php(887): OC_App::loadApps()\n#9 \/home\/segale\/domains\/segalesh.com\/public_html\/oc\/index.php(54): OC::handleRequest()\n#10 {main}","File":"\/home\/segale\/domains\/segalesh.com\/public_html\/oc\/3rdparty\/symfony\/routing\/Generator\/UrlGenerator.php","Line":177} 	2016-12-12T10:37:13+00:00
Error 	index 	Exception: {"Exception":"Symfony\\Component\\Routing\\Exception\\InvalidParameterException","Message":"Parameter \"rel_path\" for route \"collaboration_route\" must match \"[^\/]++\" (\"\" given) to generate a corresponding URL.","Code":0,"Trace":"#0 \/home\/segale\/domains\/segalesh.com\/public_html\/oc\/3rdparty\/symfony\/routing\/Generator\/UrlGenerator.php(136): Symfony\\Component\\Routing\\Generator\\UrlGenerator->doGenerate(Array, Array, Array, Array, Array, 'collaboration_r...', 1, Array, Array)\n#1 \/home\/segale\/domains\/segalesh.com\/public_html\/oc\/lib\/private\/Route\/Router.php(320): Symfony\\Component\\Routing\\Generator\\UrlGenerator->generate('collaboration_r...', Array, 1)\n#2 \/home\/segale\/domains\/segalesh.com\/public_html\/oc\/lib\/private\/URLGenerator.php(67): OC\\Route\\Router->generate('collaboration_r...', Array)\n#3 \/home\/segale\/domains\/segalesh.com\/public_html\/oc\/lib\/public\/Util.php(321): OC\\URLGenerator->linkToRoute('collaboration_r...', Array)\n#4 \/home\/segale\/domains\/segalesh.com\/public_html\/oc\/apps\/collaboration\/appinfo\/app.php(28): OCP\\Util::linkToRoute('collaboration_r...', Array)\n#5 \/home\/segale\/domains\/segalesh.com\/public_html\/oc\/lib\/private\/legacy\/app.php(187): require_once('\/home\/segale\/do...')\n#6 \/home\/segale\/domains\/segalesh.com\/public_html\/oc\/lib\/private\/legacy\/app.php(150): OC_App::requireAppFile('collaboration')\n#7 \/home\/segale\/domains\/segalesh.com\/public_html\/oc\/lib\/private\/legacy\/app.php(120): OC_App::loadApp('collaboration')\n#8 \/home\/segale\/domains\/segalesh.com\/public_html\/oc\/lib\/base.php(875): OC_App::loadApps()\n#9 \/home\/segale\/domains\/segalesh.com\/public_html\/oc\/index.php(54): OC::handleRequest()\n#10 {main}","File":"\/home\/segale\/domains\/segalesh.com\/public_html\/oc\/3rdparty\/symfony\/routing\/Generator\/UrlGenerator.php","Line":177} 	2016-12-12T10:36:59+00:00

**Comment by dlandon** [comment]
Please try the new version once uploaded to the Marketplace and report back with issues.
