### ISSUE TITLE
UI: position of paper basket icon should be in sync through apps

### ISSUE THREAD

**Issue by thommierother** [owncloud/tasks#377]
The paper basket icon used to delete entries has different positions in the different apps:
- contacts: top right
- calendar: below left
- tasks: below left (icon is different from contacts ?)

It would make life a little easier if UI could be a bit more in sync here. Tasks could have the deletion icon also top right, left of the priority icon

**Comment by dlandon** [comment]
Please try the new version once uploaded to the Marketplace and report back with issues.
