### ISSUE TITLE
 UI: useful pre-selection of calendars available for task entries

### ISSUE THREAD

**Issue by thommierother** [owncloud/tasks#378]
Currently, tasks shows all calendars which are available for the user (private, shared though OC, remote WebCAL calendars). Moreover, "contact birthdays" is shown as a separate calendar. This makes no sense, because a click on "create new task" could lead to an unsuccessful entry into "birthday calendar".

Requirement: 
Tasks should only display local OC calendars as entry points.
a) the private calendar of the user
b) shared OC calendars

"birthday calendar" should be automatically disabled (hidden).

**Comment by raimund-schluessler** [comment]
This was already discussed in https://github.com/owncloud/tasks/issues/338. It is a server issue which should be fixed in oC 9.1. See https://github.com/owncloud/core/pull/25636.
