### ISSUE TITLE
Categories are forgotten after session ends

### ISSUE THREAD

**Issue by TraceyC77** [owncloud/tasks#380]
### Steps to reproduce
1. Log into OwnCloud and to to Tasks
2. Create or edit a task and enter a category, ex: "calls"
3. Create another task, observe that the "choose categories" remembers "calls" and appears in the list under the typeahead field
4. Log out of OwnCloud
5. Log back in and go back to Tasks
6. Enter a new task and enter "calls" into the category typeahead field

### Expected behaviour
The "calls" category appears in the drop down since it was saved to an active task

### Actual behaviour
The app has no memory of the "calls" category and treats it as a new category

### Server configuration
**Operating system**: CentOS 7

### Note
As a commenter asked on apps.owncloud.com, I'm not even sure why there are categories since you can't filter or sort by them?

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.0.18 

**ownCloud version:** 9.1.4

**Tasks version:** 0.9.4

**Updated from an older ownCloud or fresh install:** Updated

**Signing status (ownCloud 9.0 and above):** n/a

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:** n/a

**The content of config/config.php:** n/a

**Comment by dlandon** [comment]
Please try the new version once uploaded to the Marketplace and report back with issues.
