### ISSUE TITLE
Title in Tasks application has some invisible [OBJ] objects? 

### ISSUE THREAD

**Issue by bartatgithub** [owncloud/tasks#381]
Hi 

Thanks for already many years one of the best Owncloud app without problems at all. 
Not a big problem but annoying: 

### Steps to reproduce
1. Owncloud Tasks sync with iOS Reminder (working without problems for many years) 
2. Owncloud 9.1 + Tasks 0.9.3 + iOS 9.3.5 + OS X El Capitan 10.11.6 
3. Old and new tasks have weird invisible, when clicked visible, [OBJ] object in title 

### Expected behaviour
Tasks title has not to have some invisible [OBJ] object in title. 

### Actual behaviour
Tasks title has some invisible [OBJ] object in title, they become visible when title is clicked. 
The amount of [OBJ] objects in title is always different. 
See screenshot, in this task title there are 5 in front of the title. 

![screen shot 2017-04-28 at 14 55 38](https://cloud.githubusercontent.com/assets/6533745/25529554/f11cdec2-2c22-11e7-9816-0840bbfffe26.png)

### Server configuration
**Operating system**: Debian Linux

**Web server:** ? 

**Database:** MySQL

**PHP version:** 7

**ownCloud version:** 9.1

**Tasks version:** 0.9.3

**Updated from an older ownCloud or fresh install: update 

**Signing status (ownCloud 9.0 and above):** ?

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:** Tasks and Calendar 

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** WebDav Owncloud Client 

### Client configuration
**Browser:** Safari

**Operating system:** Mac OS X El Capitan 

**CalDAV-clients:** Reminder 

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by dlandon** [comment]
Should be fixed in the new version I will upload to the Marketplace.

**Comment by bartatgithub** [comment]
Wow, still on that? 
Meanwhile i have moved to another cloud because i was getting crazy of this too many [OBJ].  
Sometimes more then 30. 
Anyway, thanks to fix!

**Comment by dlandon** [comment]
I am reviving the tasks app after a long time of inactivity.  I expect that this has been fixed in the latest Nextcloud tasks app and I will eventually bring the ownCloud tasks up to that version.
