### ISSUE TITLE
Issue by installing on ownCloud 9.1.5

### ISSUE THREAD

**Issue by reaphil** [owncloud/tasks#385]
After i try to activate the plugin i get the following message:

Tasks 0.9.4 
Client error response [url] https://apps.owncloud.com/CONTENT/content-files/174834-jj%3Cimg%20src= [status code] 404 [reason phrase] Not Found

**Comment by mach-o** [comment]
Duplicate of #383

**Comment by jancborchardt** [comment]
Closing as duplicate of #383, thanks @mach-o :)
