### ISSUE TITLE
Cannot reparent/unparent subtasks/parent tasks (when organizing in list view)

### ISSUE THREAD

**Issue by 0x42h** [owncloud/tasks#386]
### Steps to reproduce
1. Create a some tasks with subtasks.
2. Try to (re)parent subtasks/parent tasks.
3. Try again without avail.

### Expected behaviour
The (sub)task will be (re)parented to the (sub)task or root, when dropped on the designated drop-slot.

### Actual behaviour
The UI shows a drop-slot, but when dropped, the (sub)task reverts to it's original position.

Fails to function correctly on any version.

**Comment by dlandon** [comment]
Please try the new version once uploaded to the Marketplace and report back with issues.

**Comment by 0x42h** [comment]
Please forgive me for my belated response. 

Tried the latest version from Marketplace, Tasks 0.9.6, to no avail. 

Tried to clone this repo directly into {owncloud}/apps and still the same issue.

I am on OwnCloud 9.1. Should I upgrade to 10?
