### ISSUE TITLE
tasks & owncloud 8.1

### ISSUE THREAD

**Issue by FrancoisSauterey** [owncloud/tasks#390]
Where  can I found a OC8.1 compatible version of task? 
I've just found <8.0 or >9.0 versions... But nothing for me :-(

**Comment by amandabee** [comment]
I just checked my bash history and https://github.com/owncloud/tasks/releases/tag/v0.8 is what I installed on 8.1.1

**Comment by dlandon** [comment]
This version  of Tasks is only for 9.1 to 10.
