### ISSUE TITLE
Export and Re-Import Tasks?

### ISSUE THREAD

**Issue by amandabee** [owncloud/tasks#392]
I'm trying to make my way from 8.1x to 10.0x and my tasks all choked on the upgrade to 8.2. I need to make incremental upgrades to 10.0x so I'd love to just export my tasks from the database and reimport them, manually at the command line if that's possible.

Is that possible?

**Comment by dlandon** [comment]
I would probably sync with a client and then re-sync back to ownCloud once you update.  The other option is to download the tasks to an ics file and import it into a client and then re-sync it once you update.  The app is not ready yet in the Marketplace so you can't install it from there until I upload it to the Marketplace.
