### ISSUE TITLE
Updating Tasks and uploading to the Marketplace

### ISSUE THREAD

**Issue by dlandon** [owncloud/tasks#401]
I am making the changes necessary to get the tasks app signed and compatible with the Marketplace.  Because this version (0.9.3) is tried and true on previous ownCloud versons, I will not be making any functional changes at this time.  Once this version is on the Marketplace and is proven to be working properly, I will look to incorporate the 0.9.5 version from Nextcloud.  The original developer of the tasks app has moved to Nextcloud and is doing development there.  I will probably just track that development and possibly make some of my own enhancements.

**Comment by dlandon** [comment]
Version 0.9.3 has been uploaded to the Market.  I will work on incorporating the 0.9.5 changes from Nextcloud.

**Comment by dlandon** [comment]
I am trying to up the version in info.xml but ownCloud wants to force a marketplace update which is not successful.  What is it that is triggering this and how to I up the version without getting this update?

**Comment by DeepDiver1975** [comment]
> I am trying to up the version in info.xml but ownCloud wants to force a marketplace update which is not successful. What is it that is triggering this and how to I up the version without getting this update?

I don't get what you are saying. What is the problem?

**Comment by dlandon** [comment]
When I change the version from 0.9.3 to 0.9.5 in the info.xml file and enable the app I get this screen.
![owncloud update](https://user-images.githubusercontent.com/5514774/35040941-fa84c79c-fb50-11e7-9d74-b6eca5c99266.png)

**Comment by DeepDiver1975** [comment]
This is the expected behavior.

**Comment by dlandon** [comment]
Tasks 0.9.5 has been uploaded to the Marketplace.

**Comment by DeepDiver1975** [comment]
THX a lot!
