### ISSUE TITLE
Change list and change order does not work on owncloud 10.0.7

### ISSUE THREAD

**Issue by swanwish** [owncloud/tasks#406]
### Steps to reproduce
1. Add two lists
2. Add some tasks to one list
3. Try to move a task to the other list or try to change the task order

### Expected behaviour
I expect the task item will change the list I want to.
If I try to change the order, the task item should move to the order I placed.

### Actual behaviour
It does not change the list, and the order also not changed.

### Server configuration
**Operating system**:
CentOS 7.0

**Web server:**
nginx/1.12.2 + PHP 71w

**Database:**
MariaDB 10.2.13

**PHP version:**
php71w

**ownCloud version:** (see ownCloud admin page)
10.0.7.2

**Tasks version:** (see ownCloud apps page)
0.9.6

**Updated from an older ownCloud or fresh install:**
Updated from 10.0.6

**Signing status (ownCloud 9.0 and above):**
OK

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

**CalDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by fbassas** [comment]
Hi,
same here with ubuntu 16.04 server and owncloud 10.0.4

**Comment by dlandon** [comment]
Can someone more knowledgeable of ownCloud workings take a look at part.tasklist.php.  The drag and drop is not working.  I suspect there has been a change in 10.0.7 that has broken the drag and drop in tasks..  Thank you.

**Comment by yuranikspb** [comment]
owncloud 10.0.8.5
The drag and drop is not working.

**Comment by vovpff** [comment]
10.0.9.5 drag and drop not working for tasks.

**Comment by dlandon** [comment]
This isn't anything I will be implementing. I do not have the time to commit to learning ownCloud enough to work on this app with no compensation for my time. I would suggest you use a client that supports the functionality you want and let ownCloud be the repository for your tasks..
