### ISSUE TITLE
Cannot create new list on mobile

### ISSUE THREAD

**Issue by dschmidt** [owncloud/tasks#407]
### Steps to reproduce
1. Open App on mobile
2. Open menu
3. Click new list

### Expected behaviour
I can enter a name and create a new list.

### Actual behaviour
Menu closes immediately and new list name can't be entered and list can't be created.

### Server configuration
**Operating system**: Android 8

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** 10.0.7

**Tasks version:** 0.9.6

### Client configuration
**Browser:** Chrome

**Operating system:*** Android 8

**Comment by dlandon** [comment]
I don't understand what app you are talking about.  Sounds like an app problem to me.

**Comment by dschmidt** [comment]
Of course about the ownCloud tasks app. This repository.

**Comment by dlandon** [comment]
This app is not an Android app.  It is installed in ownCloud and accessed through a browser.  A Tasks app installed on your phone can access this app for tasks information.  If you feel that this is the app you are concerned with, please post a screenshot of the app you are having trouble with.

**Comment by dschmidt** [comment]
Noone said this was an Android app.
I'm aware that this is an ownCloud app and what ownCloud apps are. Maybe take a look who submitted the initial ldap app :-p

I just said that the html ui is broken in Chrome on Android. Most probably also on other touch devices, but as I don't own any I can't tell.

**Comment by dlandon** [comment]
"Open App on mobile" sort of implies an Android app.  It would have been better to say accessing ownCloud through a browser on an Android device in your original post.

**Comment by dlandon** [comment]
I do not have the time to commit to learning ownCloud enough to work on this app with no compensation for my time. I would suggest you use a client that supports the functionality you want and let ownCloud be the repository for your tasks..
