### ISSUE TITLE
Unable to share tasks between users

### ISSUE THREAD

**Issue by YugieDev** [owncloud/tasks#408]
### Steps to reproduce
None

### Expected behavior
You should be able to share to-do lists with other users

### Actual behavior
There is no clear way of sharing to-do lists or tasks with other users

### Server configuration
**Operating system**: Linux Ubuntu 16.04

**Web server:** Apache2

**Database:** MySQL

**PHP version:** 7.0

**ownCloud version:** 10.0.8

**Tasks version:** 0.9.6

**Updated from an older ownCloud or fresh install:** Fresh install

**Signing status (ownCloud 9.0 and above):** None

No errors have been found.

**Comment by fsteinbauer** [comment]
+1

**Comment by johnwayne4d** [comment]
+1

**Comment by Dubwize** [comment]
+1

**Comment by julianpoemp** [comment]
+1

**Comment by xetyr** [comment]
+1

**Comment by vollknorke1337** [comment]
Hi there.
Any chance to get this working? I am not able to share Tasks with users or groups also. Even not with the calendar workaround. Using OC 10.1.1.1

**Comment by gjeempe** [comment]
Almost year passed since last comment. Any chances for sharing tasks? Without that _basic_ functionality whole app is useless.

**Comment by DeepDiver1975** [comment]
Nobody is maintaining this app - nothing will happen in the upcoming years - sorry

**Comment by dlandon** [comment]
I do not have the time to commit to learning ownCloud enough to work on this app with no compensation for my time. I would suggest you use a client that supports the functionality you want and let ownCloud be the repository for your tasks..
