### ISSUE TITLE
Priority settings for tasks have wrong  sequence

### ISSUE THREAD

**Issue by thommierother** [owncloud/tasks#409]
1. Connect CalDAV calender, e.g. to KDE/Akonadi KOrganizer or other CaldAV based tasks management
2. enter task and set priority to "1" (highest)
3. Tasks UI shows "priority 1" as "lowest" 

### Expected behaviour
Priority 1 should be highest and priority 9 should be lowest. 

### Actual behaviour
Wrong sequence. This looks like an UI issue ...

### Server configuration
**Operating system**:
Ubuntu 16 LTS

**Web server:**
Apache 2.4.x

**Database:**
MariaDB

**PHP version:**
7.x

**ownCloud version:** (see ownCloud admin page)
10.0.8

**Tasks version:** (see ownCloud apps page)
0.9.6 

**Updated from an older ownCloud or fresh install:**
updated

**Signing status (ownCloud 9.0 and above):**
signed app
```

**Comment by dlandon** [comment]
I do not have the time to commit to learning ownCloud enough to work on this app with no compensation for my time. I would suggest you use a client that supports the functionality you want and let ownCloud be the repository for your tasks..
