### ISSUE TITLE
Tasks are not displayed in IE 11

### ISSUE THREAD

**Issue by dr-brown** [owncloud/tasks#410]
### Steps to reproduce
1. open Tasks-App in IE 11 (possibly the problem exists also in older versions)

### Expected behaviour
The task app should appear
(In the FireFox everything works completely)

### Actual behaviour
nothing but the header is displayed

### Server configuration
**ownCloud version:** 10.0.4

**Tasks version:** 0.9.6

### Client configuration
**Browser:** IE 11

**Operating system:** Windows 7

#### Browser log
a) The javascript console log

SCRIPT1003: ':' erwartet
Datei: app.js, Zeile: 4411, Spalte: 22

SCRIPT5022: [$injector:modulerr] http://errors.angularjs.org/1.5.5/$injector/modulerr?p0=Tasks&p1=Error%3A%20%5B%24injector%3Anomod%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.5.5%2F%24injector%2Fnomod%3Fp0%3DTasks%0A%20%20%20at%20Anonymous%20function%20(https%3A%2F%2Fcloud.millerstudios.de%2Fapps%2Ftasks%2Fjs%2Fvendor%2Fangular%2Fangular.min.js%3Fv%3Db2880fb1aa8b0ad6191afa754e2a1b5a%3A25%3A229)%0A%20%20%20at%20b%20(https%3A%2F%2Fcloud.millerstudios.de%2Fapps%2Ftasks%2Fjs%2Fvendor%2Fangular%2Fangular.min.js%3Fv%3Db2880fb1aa8b0ad6191afa754e2a1b5a%3A24%3A263)%0A%20%20%20at%20Anonymous%20function%20(https%3A%2F%2Fcloud.millerstudios.de%2Fapps%2Ftasks%2Fjs%2Fvendor%2Fangular%2Fangular.min.js%3Fv%3Db2880fb1aa8b0ad6191afa754e2a1b5a%3A25%3A13)%0A%20%20%20at%20Anonymous%20function%20(https%3A%2F%2Fcloud.millerstudios.de%2Fapps%2Ftasks%2Fjs%2Fvendor%2Fangular%2Fangular.min.js%3Fv%3Db2880fb1aa8b0ad6191afa754e2a1b5a%3A39%3A372)%0A%20%20%20at%20q%20(https%3A%2F%2Fcloud.millerstudios.de%2Fapps%2Ftasks%2Fjs%2Fvendor%2Fangular%2Fangular.min.js%3Fv%3Db2880fb1aa8b0ad6191afa754e2a1b5a%3A7%3A353)%0A%20%20%20at%20g%20(https%3A%2F%2Fcloud.millerstudios.de%2Fapps%2Ftasks%2Fjs%2Fvendor%2Fangular%2Fangular.min.js%3Fv%3Db2880fb1aa8b0ad6191afa754e2a1b5a%3A39%3A222)%0A%20%20%20at%20bb%20(https%3A%2F%2Fcloud.millerstudios.de%2Fapps%2Ftasks%2Fjs%2Fvendor%2Fangular%2Fangular.min.js%3Fv%3Db2880fb1aa8b0ad6191afa754e2a1b5a%3A43%3A240)%0A%20%20%20at%20c%20(https%3A%2F%2Fcloud.millerstudios.de%2Fapps%2Ftasks%2Fjs%2Fvendor%2Fangular%2Fangular.min.js%3Fv%3Db2880fb1aa8b0ad6191afa754e2a1b5a%3A21%3A17)%0A%20%20%20at%20yc%20(https%3A%2F%2Fcloud.millerstudios.de%2Fapps%2Ftasks%2Fjs%2Fvendor%2Fangular%2Fangular.min.js%3Fv%3Db2880fb1aa8b0ad6191afa754e2a1b5a%3A21%3A325)%0A%20%20%20at%20ee%20(https%3A%2F%2Fcloud.millerstudios.de%2Fapps%2Ftasks%2Fjs%2Fvendor%2Fangular%2Fangular.min.js%3Fv%3Db2880fb1aa8b0ad6191afa754e2a1b5a%3A20%3A156)
Datei: angular.min.js, Zeile: 40, Spalte: 25

**Comment by dlandon** [comment]
Internet Explorer is being phased out and is not worth the effort to make tasks compatible.  Use another browser.
