### ISSUE TITLE
Unable to edit task title if accidentally saved with a blank field

### ISSUE THREAD

**Issue by chc-pr** [owncloud/tasks#414]
### Steps to reproduce
1. create a task related to a calendar
2. 'rename' the task with a blank field
3. try to rename the field again

### Expected behaviour
be able to create a new task descriptor name

### Actual behaviour
Unable to enter teh edit field
### Server configuration
**Operating system**:
Ubuntu 18.04

**Web server:**
Apache2

**Database:**
 Ver 15.1 Distrib 10.3.18-MariaDB, for debian-linux-gnu (x86_64)

**PHP version:**
PHP 7.2.19-0ubuntu0.18.04.2 

**ownCloud version:** (see ownCloud admin page)
10.2.1.4

**Tasks version:** (see ownCloud apps page)
0.9.7
**Updated from an older ownCloud or fresh install:**
Updated from 10.2.0.5

**Signing status (ownCloud 9.0 and above):**
No failed signings or integrity failures reported
```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**
n/a

**The content of config/config.php:**
n/a

**Are you using external storage, if yes which one:** local/smb/sftp/...
n/a

**Are you using encryption:** yes/no
n/a

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
openLDAP, but n/a

### Client configuration
**Browser:**
Firefox Quantum 69.0.1 (64-bit)
also 
Version 77.0.3865.90 (Official Build) (64-bit)

**Operating system:**
Windows 10

**CalDAV-clients:**
Calendar, but n/a

**Comment by dlandon** [comment]
I do not have the time to commit to learning ownCloud enough to work on this app with no compensation for my time. I would suggest you use a client that supports the functionality you want and let ownCloud be the repository for your tasks..
