### ISSUE TITLE
Sub tasks cannot be saved in OwnCloud 17

### ISSUE THREAD

**Issue by mritchie76** [owncloud/tasks#415]
### Steps to reproduce
1. Add sub task
2. Move into other app then back into tasks
3. Sub task is not there

### Expected behaviour
Sub task is saved, can be set as a favourite and could have a subsequent sub task added

### Actual behaviour
Sub task disappears when navigating away and then back

### Server configuration
Ubuntu 18.04

**Web server:**
Apache
**Database:**
MySQL
**PHP version:**
7.2.24
**ownCloud version:** (see ownCloud admin page)
17.0.1
**Tasks version:** (see ownCloud apps page)
0.11.3
**Updated from an older ownCloud or fresh install:**
Updated
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes - local
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
Chrome
**Operating system:**
Win10
**CalDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by DeepDiver1975** [comment]
> **ownCloud version:** (see ownCloud admin page)
> 17.0.1

ownCloud is currently at 10.3.x - I suspect you are using nextcloud -> https://github.com/nextcloud
