### ISSUE TITLE
Commata in task titles are (possibly) incorrectly escaped

### ISSUE THREAD

**Issue by HackintoshHD** [owncloud/tasks#44]
Entering something like

`This is a test with commata, commata, commata …`

is correctly displayed at first by Tasks Enhanced, but ends up as

`This is a test with commata\, commata\, commata …`

in the app's web interface after some minutes:

![tasks_enhanced_bug](https://cloud.githubusercontent.com/assets/2894628/3689313/fb3de0c2-133e-11e4-9cd3-99014acfbcea.png)

At this point, I am not sure if this is a problem of Tasks Enhanced or of either the iOS or OS X Clients modifying something in the title (although I would assume they're not, as long as you do not edit the specific task, which I did not).

**Comment by alfish2000** [comment]
Here is a little fix which seems to work:

	 controller/helper.php | 2 +-
	 1 file changed, 1 insertion(+), 1 deletion(-)

	diff --git a/controller/helper.php b/controller/helper.php
	index 11db7b5..274e4ef 100644
	--- a/controller/helper.php
	+++ b/controller/helper.php
	@@ -35,7 +35,7 @@ Class Helper {
	 
		public static function arrayForJSON($id, $vtodo, $user_timezone){
			$task = array( 'id' => $id );
	-		$task['name'] = $vtodo->getAsString('SUMMARY');
	+		$task['name'] = strtr($vtodo->getAsString('SUMMARY'), array('\,' => ',', '\;' => ';'));
			$task['created'] = $vtodo->getAsString('CREATED');
			$task['note'] = $vtodo->getAsString('DESCRIPTION');
			$task['location'] = $vtodo->getAsString('LOCATION');

It is based on how the calendar app is doing it (app.php line 486):

    'title' => (!is_null($vevent->SUMMARY) && $vevent->SUMMARY->value != '')? strtr($vevent->SUMMARY->value, array('\,' => ',', '\;' => ';')) : self::$l10n->t('unnamed'),

The comma is escaped in the database as well and it seems that it is just unescaped in each client before displaying the string.

**Comment by raimund-schluessler** [comment]
The problem with this solution currently is that already escaped commata and semicolons are not escaped a second time. So a task title like "Test , ; \; \," becomes "Test .; ; ," which is not quite what we want. I guess we have to manually escape them before writing it to the database.

**Comment by raimund-schluessler** [comment]
By the way: The calendar app has the same problem ;)

**Comment by alfish2000** [comment]
Yes. But it would be in sync with the calendar app at least. :-)

**Comment by raimund-schluessler** [comment]
With the current master (oC 8.1) and the update to SabreDAV 2.1 and the related VObject library everything seems to work correctly now. Would be cool if you could test with oC 8.1 and this branch https://github.com/owncloud/tasks/tree/sabre-upgrade2.1 of the tasks app.

**Comment by alfish2000** [comment]
Sorry, but I'm still on ownCloud 8.0.3 (stable) on my server.
When I get 8.1 via packet manager I can test that.

**Comment by alfish2000** [comment]
Updated to OC 8.1 yesterday.
The commas and semicolons look fine now.
