### ISSUE TITLE
Share tasks

### ISSUE THREAD

**Issue by Chais** [owncloud/tasks#47]
It would be nice to be able to share tasks to other users. Possibly via some sort of assignment. So tasks could be assigned to one or more users and then appear in their lists as well.
If a user changes the task's completion or adds a comment the other assignees should see the change.
A user could be given the possibility to reject a task. In that case the task shouldn't appear on that user's list but should not be deleted and still appear on the other assignee's lists. The creator of the task could receive a notification in that case.

**Comment by e-alfred** [comment]
Anything new on this issue? Owncloud is now at 9.1 and this feature would be great for users to share tasks with their status/due date/start date and so on.
