### ISSUE TITLE
Support todo.txt format

### ISSUE THREAD

**Issue by Matthias84** [owncloud/tasks#59]
Hi, it would be great, if you might consider http://todotxt.com standard so users can edit their tasks if they alter an virtual todo.txt file for example via webdav.

**Comment by nodiscc** [comment]
@Matthias84 You can already use the todo.txt format in your tasks (e.g I use `@shopping` `@work`). The main thing missing is having a **file backend** (like auto-storing and reading tasks from a `tasks.txt` file), but not everyone is going to want this. It also needs filtering capabilities to be really useful (https://github.com/owncloud/tasks/issues/117).

@raimund-schluessler What do you think? wontfix?

**Comment by raimund-schluessler** [comment]
Well, I don't think the todo.txt format is suitable at all for this app here. As I understand it, todo.txt does aim on simplicity and therefore does not support a variety of features that CalDAV does and which are used here (Start / End dates, notes, Reminders, Comments, Sharing tasks with other users, etc.). So if you want to use Todo.txt this means losing all this, which would result in a totally different app.

You could of course implement a backend which does store everything in a todo.txt and give the user the choice to either use todo.txt format or CalDAV with additional features, but I guess in this case it would be better to write an own app only for todo.txt (feel free to use the code base of this app here ;).

Closing this issue as I won't implement it. Reopen if you think differently. 

Regards.
