### ISSUE TITLE
Assign users to tasks

### ISSUE THREAD

**Issue by raimund-schluessler** [owncloud/tasks#7]
For a proper collaboration support it is necessary to assign users to tasks. To enable this feature https://github.com/raimund-schluessler/tasks_enhanced/issues/6 must be implemented first.

**Comment by RudolfVonKrugstein** [comment]
+1

**Comment by dedenker** [comment]
+1

**Comment by keunes** [comment]
+1
Any priority given to this issue? 0:)

**Comment by raimund-schluessler** [comment]
Priority is currently on https://github.com/owncloud/tasks/pull/291, otherwise Tasks won't work on oC9. With CalDAV in core it might get easier to solve this issue here too.

**Comment by keunes** [comment]
@raimund-schluessler Thanks for the info!

**Comment by philxtian** [comment]
+1

**Comment by SaerAlmukhlfi** [comment]
+1

**Comment by SaerAlmukhlfi** [comment]
did this will be in the next release ?

**Comment by SaerAlmukhlfi** [comment]
I saw it labeled enhancement , how I can use it at OC8.2 ?

**Comment by keunes** [comment]
@SaerAlmukhlfi It has not been implemented yet and so you cannot use it yet. First issue #291 must be solved, so I *don't* think it will be possible soon.
